---
permalink: api-changes.html 
sidebar: sidebar 
keywords: rest api, api changes, parameters, default values, breaking changes, documentation errors 
summary: NetApp은 각 주요 제품 릴리즈별로 ONTAP REST API를 계속해서 개선하고 업데이트합니다. 이러한 업데이트에는 사용된 매개 변수와 기본값 등 기존 API 호출에 대한 변경 사항이 포함될 수 있습니다. 이러한 변경은 REST API에 액세스하는 소프트웨어에 영향을 미칠 수 있습니다. 
---
= ONTAP REST API 호출의 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 각 주요 제품 릴리즈별로 ONTAP REST API를 계속해서 개선하고 업데이트합니다. 이러한 업데이트에는 사용된 매개 변수와 기본값 등 기존 API 호출에 대한 변경 사항이 포함될 수 있습니다. 이러한 변경은 REST API에 액세스하는 소프트웨어에 영향을 미칠 수 있습니다.



== 기존 ONTAP REST API 호출에 대한 변경 사항

기존 API 호출을 변경하면 REST API에 액세스하는 소프트웨어에 영향을 미칠 수 있습니다. 아래 표의 변경 목록을 검토하여 ONTAP 자동화 환경에 영향을 미치는지 확인해야 합니다. 각 항목에는 적용 가능한 API 끝점, 변경 설명 및 도입된 ONTAP 릴리스가 포함됩니다.

[cols="40%,50%,10%"]
|===
| 엔드포인트 | 변경에 대한 설명 | ONTAP 릴리즈 


| `/security/authentication/duo/groups`
`/security/authentication/duo/profiles` | 응답의 *_links * 필드가 이러한 끝점의 이중 그룹에서 제거되었습니다. 권장되는 고객 조치 또는 해결 방법이 없습니다. 이 필드는 향후 ONTAP 릴리즈에서 다시 추가될 예정입니다. | 9.15.1 
|===


== ONTAP REST API 참조 문서 오류

NetApp에서 ONTAP REST API를 개선 및 업데이트함에 따라 온라인 참조 문서에 오류가 발생할 수도 있습니다. 이러한 오류는 API를 사용할 때 혼동을 일으킬 수 있지만 일반적으로 ONTAP 자동화 소프트웨어 또는 환경에 영향을 미치거나 영향을 주지 않습니다.

아래 표에서 오류 목록을 검토해야 합니다. 그러면 ONTAP REST API 참조 문서를 더 잘 이해하고 탐색하는 데 도움이 됩니다. 각 항목에는 해당 API 끝점, 오류에 대한 설명 및 도입된 ONTAP 릴리스가 포함됩니다.

[cols="40%,50%,10%"]
|===
| 엔드포인트 | 변경에 대한 설명 | ONTAP 릴리즈 


| `/storage/quota/reports` | 끝점에 대한 REST API 문서는 * specifier * 가 유효한 필드임을 나타냅니다. 그러나 이 끝점에서는 할당량 지정자가 지원되지 않습니다. 권장되는 고객 조치 또는 해결 방법이 없습니다. 이 필드는 향후 ONTAP 릴리스의 API 설명서에서 제거될 예정입니다. | 9.6 
|===
.관련 정보
link:whats-new.html["ONTAP REST API의 새로운 기능"]
