---
sidebar: sidebar 
permalink: new_ontap_automation.html 
keywords: new features 
summary: ONTAP의 현재 릴리즈에는 여러 가지 새로운 자동화 기능과 변경된 자동화 기능이 있습니다. 
---
= ONTAP 9.10.1 자동화의 새로운 기능
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
현재 ONTAP 릴리즈에는 몇 가지 새로운 자동화 기능과 변경된 자동화 기능이 포함되어 있습니다.



=== ONTAP 9.10.1 REST API

ONTAP 9.10.1 ONTAP REST API의 기능은 계속 확장되고 있습니다. 새로운 ONTAP 기능과 기존 기능 향상을 지원하기 위해 100개 이상의 새로운 엔드포인트가 추가되었습니다. REST API의 향상된 기능에 대한 요약 정보가 아래에 나와 있습니다.

애플리케이션 정합성 보장 그룹:: 정합성 보장 그룹은 스냅샷과 같은 특정 작업을 수행할 때 함께 그룹화되는 볼륨 세트입니다. 이 기능은 단일 볼륨 작업에서 동일한 충돌 일관성 및 데이터 무결성을 단일 볼륨 작업으로 확장합니다. 대규모 다중 볼륨 워크로드 애플리케이션에 유용합니다.
SVM 마이그레이션:: 소스 클러스터에서 대상 클러스터로 SVM을 마이그레이션할 수 있습니다. 새 엔드포인트는 일시 중지, 재개, 상태 검색 및 마이그레이션 작업 중단 기능을 포함하여 완벽한 제어를 제공합니다.
파일 복제 및 관리:: 볼륨 레벨 파일 클론 복제 및 관리가 개선되었습니다. 새로운 REST 엔드포인트는 파일 이동, 복사 및 분할 작업을 지원합니다.
S3 감사 기능 향상:: S3 이벤트에 대한 감사는 특정 S3 이벤트를 추적하고 기록할 수 있는 보안 개선입니다. S3 감사 이벤트 선택기는 버킷당 SVM 단위로 설정할 수 있습니다.
랜섬웨어 방어:: ONTAP는 랜섬웨어 위협이 있을 가능성이 있는 파일을 감지합니다. 이러한 의심되는 파일의 목록을 검색할 수 있을 뿐 아니라 볼륨에서 제거할 수도 있습니다.
기타 보안 향상 기능:: 기존 프로토콜을 확장하고 새로운 기능을 도입하는 몇 가지 일반적인 보안 개선 사항이 있습니다. IPsec, 키 관리, SSH 구성 및 파일 권한이 개선되었습니다.
CIFS 도메인 및 로컬 그룹:: CIFS 도메인에 대한 지원이 클러스터 및 SVM 레벨에서 추가되었습니다. 도메인 구성을 검색할 뿐만 아니라 기본 도메인 컨트롤러를 만들고 제거할 수도 있습니다.
볼륨 분석 확장:: 추가 엔드포인트를 통해 볼륨 분석 및 메트릭이 확장되어 상위 파일, 디렉토리 및 사용자를 지원합니다.
지원 개선 사항:: 몇 가지 새로운 기능을 통해 지원이 향상되었습니다. 자동 업데이트는 최신 소프트웨어 업데이트를 다운로드하고 적용하여 ONTAP 시스템을 최신 상태로 유지할 수 있습니다. 노드에서 생성된 메모리 코어 덤프를 검색하고 관리할 수도 있습니다.

