---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP 자동화 문서
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: migrate
  - section: additional
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 릴리즈 노트
      url: "/rn/whats_new.html"
    - title: ONTAP 자동화 옵션
      url: "/get-started/ontap_automation_options.html"
    - title: REST API 사용 준비
      url: "/get-started/prepare.html"
    - title: 헬로우 월드
      url: "/get-started/hello_world.html"
  - title: ONTAP REST API를 참조하십시오
    links:
    - title: REST 구현 세부 정보
      url: "/rest/rest_web_services_foundation.html"
    - title: 추가 고려 사항
      url: "/rest/object_references_and_access.html"
    - title: 나머지 리소스 요약
      url: "/resources/overview_categories.html"
    - title: API 참조입니다
      url: "/reference/api_reference.html"
  - title: 자동화
    links:
    - title: Python 클라이언트 라이브러리
      url: "/python/overview_pcl.html"
    - title: ONTAP 및 Ansible
      url: "/automate/ontap_ansible.html"
    - title: 자동화 블로그
      url: "/automate/blogs.html"
  - title: 더 많은 리소스
    links:
    - title: 자세한 정보를 확인하십시오
      url: "/additional/get_more_information.html"
    - title: NetApp DevNet을 참조하십시오
      url: https://devnet.netapp.com/restapi.php
    - title: ONTAP 9 문서
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select 문서
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: 모든 ONTAP 제품 설명서
