---
sidebar: sidebar 
permalink: whats_new.html 
keywords: new features, new in release 
summary: NetApp은 새로운 기능, 개선 사항 및 버그 수정을 제공하기 위해 ONTAP REST API를 정기적으로 업데이트합니다. 
---
= ONTAP REST API 및 자동화의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 새로운 기능, 개선 사항 및 버그 수정을 제공하기 위해 ONTAP REST API를 정기적으로 업데이트합니다.


TIP: 또한 를 검토해야 합니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 릴리즈 노트"^] 알려진 제한 사항 또는 문제를 포함한 추가 정보



== ONTAP 9.13.1

ONTAP 9.13.1 ONTAP REST API의 기능을 20개 이상의 새로운 API 호출로 계속 확장하고 있습니다. 이러한 엔드포인트는 새로운 ONTAP 기능과 기존 기능의 향상된 기능을 지원합니다. 이 릴리즈에서는 보안, 리소스 관리, 향상된 SVM 구성 옵션, 성능 메트릭 등의 개선 사항에 중점을 둡니다.

리소스 태그 지정:: 태그를 사용하여 REST API 리소스를 그룹화할 수 있습니다. 이렇게 하면 특정 프로젝트 또는 조직 그룹 내의 관련 자원을 연결할 수 있습니다. 태그를 사용하면 리소스를 보다 효율적으로 구성 및 추적할 수 있습니다.
정합성 보장 그룹:: ONTAP 9.13.1 성능 카운터 데이터의 가용성을 지속적으로 확장합니다. 이제 이 유형의 통계 정보에 액세스하여 정합성 보장 그룹의 기간별 성능 및 용량을 추적할 수 있습니다. 또한 정합성 보장 그룹 간의 상위-하위 관계를 구성 및 관리할 수 있는 향상된 기능도 포함되었습니다.
SVM당 DNS 구성:: 개별 SVM에 대해 DNS 도메인 및 서버 구성을 수행할 수 있도록 기존 DNS 엔드포인트를 확장하였습니다.
EMS 역할 구성:: 기존 EMS 지원 기능이 확장되어 역할에 할당된 역할 및 액세스 제어 구성을 관리할 수 있습니다. 이렇게 하면 역할 구성에 따라 이벤트 및 메시지를 제한하거나 필터링할 수 있습니다.
보안:: REST API를 사용하여 SSH를 사용하여 ONTAP에 로그인하고 액세스하는 계정에 대해 TOTP(Time-Based One-Time Password) 프로필을 구성할 수 있습니다. 또한 키 관리자 끝점이 확장되어 지정된 키 관리 서버에서 복구 작업을 제공합니다.
SVM당 CIFS 구성:: 특정 SVM에 대한 구성을 업데이트할 수 있도록 기존 CIFS 엔드포인트가 확장되었습니다.
S3 버킷 규칙:: 기존 S3 버킷 끝점이 규칙 정의를 포함하도록 확장되었습니다. 각 규칙은 목록 오브젝트이며 버킷 내의 오브젝트에 대해 수행할 동작 집합을 정의합니다. 전체적으로 이러한 규칙을 통해 S3 버킷의 라이프사이클을 보다 효율적으로 관리할 수 있습니다.




== ONTAP 9.12.1

ONTAP 9.12.1은 40개 이상의 새로운 API 호출을 통해 ONTAP REST API의 기능을 계속 확장하고 있습니다. 이러한 엔드포인트는 새로운 ONTAP 기능과 기존 기능의 향상된 기능을 지원합니다. 이 릴리즈는 보안 및 NAS 기능 향상에 중점을 둡니다.

보안 강화:: Amazon Web Services에는 키 및 기타 비밀에 대한 보안 저장소를 제공하는 키 관리 서비스가 포함되어 있습니다. REST API를 통해 이 서비스에 액세스하여 ONTAP에서 클라우드에 암호화 키를 안전하게 저장할 수 있습니다. 또한 NetApp Storage Encryption에 사용되는 인증 키를 생성하고 나열할 수 있습니다.
Active Directory를 클릭합니다:: ONTAP 클러스터에 대해 정의된 Active Directory 계정을 관리할 수 있습니다. 여기에는 새 계정 만들기와 계정 표시, 업데이트 및 삭제 작업이 포함됩니다.
CIFS 그룹 정책입니다:: REST API는 CIFS 그룹 정책의 생성 및 관리를 지원하도록 개선되었습니다. 구성 정보는 모든 또는 특정 SVM에 적용되는 그룹 정책 개체를 통해 사용 및 관리됩니다.




== ONTAP 9.11.1

ONTAP 9.11.1은 거의 100개의 새로운 API 호출을 통해 ONTAP REST API의 기능을 계속 확장하고 있습니다. 이러한 엔드포인트는 새로운 ONTAP 기능과 기존 기능의 향상된 기능을 지원합니다. 이 릴리즈에서는 고객이 Data ONTAP API(ONTAPI 또는 ZAPI)에서 ONTAP REST API로 마이그레이션할 수 있도록 지원합니다.

세분화된 RBAC:: RBAC(ONTAP 역할 기반 액세스 제어) 기능이 더 세분화하여 개선되었습니다. REST API를 통해 필요에 따라 기존 역할을 사용하거나 새 사용자 지정 역할을 생성할 수 있습니다. 모든 역할은 하나 이상의 권한과 연결되며, 각 권한은 액세스 수준과 함께 REST API 호출 또는 CLI 명령을 식별합니다. READ_CREATE 및 READ_MODIFY과 같은 REST 역할에 대해 새로운 액세스 수준을 사용할 수 있습니다. 이러한 향상 기능은 Data ONTAP API(ONTAPI 또는 ZAPI)와 패리티를 제공하고 REST API로 고객 마이그레이션을 지원합니다. 을 참조하십시오 link:../rest/rbac_overview.html["RBAC 보안"] 를 참조하십시오.
성능 카운터:: 이전 ONTAP 릴리즈에서는 시스템의 작동 특성에 대한 통계 정보를 유지했습니다. 9.11.1 릴리스 버전에서는 이 정보가 향상되어 이제 REST API를 통해 사용할 수 있습니다. 관리자 또는 자동화된 프로세스에서 데이터에 액세스하여 시스템 성능을 확인할 수 있습니다. 카운터 관리자 하위 시스템에서 유지 관리하는 통계 정보는 테이블 및 행을 사용하여 데이터베이스 형식으로 표시됩니다. 이러한 성능 향상을 통해 ONTAP REST API는 Data ONTAP API(ONTAPI 또는 ZAPI)와 패리티에 더 가깝게 됩니다.
애그리게이트 관리:: ONTAP 스토리지 애그리게이트 관리가 향상되었습니다. 업데이트된 REST 엔드포인트를 사용하여 온라인 및 오프라인으로 애그리게이트를 이동하고 스페어를 관리할 수 있습니다.
IP 서브넷 기능입니다:: ONTAP 네트워킹 기능이 IP 서브넷 지원을 포함하도록 확장되었습니다. REST API를 사용하면 ONTAP 클러스터 내에서 IP 서브넷의 구성 및 관리에 액세스할 수 있습니다.
여러 관리자 검증:: 여러 관리자 확인 기능은 ONTAP 명령 또는 작업에 대한 액세스를 보호하기 위한 유연한 인증 프레임워크를 제공합니다. 제한된 명령을 식별하는 규칙을 정의할 수 있습니다. 사용자가 특정 명령에 대한 액세스를 요청하면 여러 ONTAP 관리자가 적절한 승인을 부여할 수 있습니다.
SnapMirror의 향상된 기능:: SnapMirror 기능은 예약을 비롯한 여러 영역에서 개선되었습니다. SnapVault 관계 패리티는 ONTAP 9.11.1과 DP 관계에 추가되었으며, REST API에서 사용할 수 있는 스로틀 기능은 Data ONTAP API(ONTAPI 또는 ZAPI)와 동일합니다. 이와 관련하여 대량 스냅샷 복사본을 생성 및 관리할 수 있는 지원이 제공됩니다.
지원합니다:: ONTAP 스토리지 풀에 대한 액세스를 제공하기 위해 여러 엔드포인트가 추가되었습니다. 클러스터에서 스토리지 풀을 생성 및 나열하고 ID별로 특정 풀을 업데이트 및 삭제하는 기능이 지원됩니다.
이름 서비스 캐시 지원:: ONTAP 이름 서비스는 성능 및 복원성을 향상시키는 캐싱을 지원하도록 개선되었습니다. 이제 REST API를 통해 이름 서비스 캐시 구성에 액세스할 수 있습니다. 호스트, UNIX 사용자, UNIX 그룹 및 넷그룹을 비롯한 여러 레벨에서 설정을 적용할 수 있습니다.
ONTAPI 보고 도구:: ONTAPI 보고 도구는 고객과 파트너가 자신의 환경에서 ONTAPI 사용을 식별할 수 있도록 도와줍니다. Python 소프트웨어 외에도 NetApp Lab on Demand의 비디오 및 발전 지원도 제공됩니다. 이 툴은 ONTAPI에서 ONTAP REST API로 마이그레이션할 때 다른 리소스를 제공합니다.




== ONTAP 9.10.1

ONTAP 9.10.1 ONTAP REST API의 기능은 계속 확장되고 있습니다. 새로운 ONTAP 기능과 기존 기능 향상을 지원하기 위해 100개 이상의 새로운 엔드포인트가 추가되었습니다. REST API의 향상된 기능에 대한 요약 정보가 아래에 나와 있습니다.

애플리케이션 정합성 보장 그룹:: 정합성 보장 그룹은 스냅샷과 같은 특정 작업을 수행할 때 함께 그룹화되는 볼륨 세트입니다. 이 기능은 단일 볼륨 작업에서 동일한 충돌 일관성 및 데이터 무결성을 단일 볼륨 작업으로 확장합니다. 대규모 다중 볼륨 워크로드 애플리케이션에 유용합니다.
SVM 마이그레이션:: 소스 클러스터에서 대상 클러스터로 SVM을 마이그레이션할 수 있습니다. 새 엔드포인트는 일시 중지, 재개, 상태 검색 및 마이그레이션 작업 중단 기능을 포함하여 완벽한 제어를 제공합니다.
파일 복제 및 관리:: 볼륨 레벨 파일 클론 복제 및 관리가 개선되었습니다. 새로운 REST 엔드포인트는 파일 이동, 복사 및 분할 작업을 지원합니다.
S3 감사 기능 향상:: S3 이벤트에 대한 감사는 특정 S3 이벤트를 추적하고 기록할 수 있는 보안 개선입니다. S3 감사 이벤트 선택기는 버킷당 SVM 단위로 설정할 수 있습니다.
랜섬웨어 방어:: ONTAP는 랜섬웨어 위협이 있을 가능성이 있는 파일을 감지합니다. 이러한 의심되는 파일의 목록을 검색할 수 있을 뿐 아니라 볼륨에서 제거할 수도 있습니다.
기타 보안 향상 기능:: 기존 프로토콜을 확장하고 새로운 기능을 도입하는 몇 가지 일반적인 보안 개선 사항이 있습니다. IPsec, 키 관리, SSH 구성 및 파일 권한이 개선되었습니다.
CIFS 도메인 및 로컬 그룹:: CIFS 도메인에 대한 지원이 클러스터 및 SVM 레벨에서 추가되었습니다. 도메인 구성을 검색할 뿐만 아니라 기본 도메인 컨트롤러를 만들고 제거할 수도 있습니다.
볼륨 분석 확장:: 추가 엔드포인트를 통해 볼륨 분석 및 메트릭이 확장되어 상위 파일, 디렉토리 및 사용자를 지원합니다.
지원 개선 사항:: 몇 가지 새로운 기능을 통해 지원이 향상되었습니다. 자동 업데이트는 최신 소프트웨어 업데이트를 다운로드하고 적용하여 ONTAP 시스템을 최신 상태로 유지할 수 있습니다. 노드에서 생성된 메모리 코어 덤프를 검색하고 관리할 수도 있습니다.




== ONTAP 9.9.1

ONTAP 9.9.1은 ONTAP REST API의 기능을 계속 확장합니다. SAN 포트 세트 및 SVM 파일 디렉토리 보안을 비롯한 기존 ONTAP 기능을 위한 새로운 API 엔드포인트가 있습니다. 또한 새로운 ONTAP 9.9.1 기능 및 향상된 기능을 지원하기 위해 끝점이 추가되었습니다. 또한 관련 문서도 개선되었습니다. 개선 사항에 대한 요약은 아래에 나와 있습니다.

ONTAP 9 REST API에 ONTAPI 매핑:: ONTAP 자동화 코드를 REST API로 전환할 수 있도록 NetApp에서 API 매핑 문서를 제공합니다. 이 참조에는 ONTAPI 호출 목록과 각각에 해당하는 REST API 호출 목록이 포함되어 있습니다. 새 ONTAP 9.9.1 API 끝점을 포함하도록 매핑 문서가 업데이트되었습니다. 을 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2876895["ONTAPI를 REST API 매핑에 매핑"^] 를 참조하십시오.
새로운 ONTAP 9.9.1 코어 기능의 API 엔드포인트:: ONTAPI API를 통해 사용할 수 없는 새로운 ONTAP 9.9.1 기능이 REST API에 추가되었습니다. 여기에는 중첩된 igroup 및 Google Cloud Key Management Services에 대한 지원이 포함됩니다.
ONTAPI에서 REST로 전환하기 위한 지원이 향상되었습니다:: 기존 ONTAPI 호출의 더 많은 부분이 이제 상응하는 REST API 호출을 갖게 되었습니다. 여기에는 로컬 Unix 사용자 및 그룹, 클라이언트, SAN 포트 세트 및 볼륨 공간 속성 없이 NTFS 파일 보안 관리가 포함됩니다. 이러한 변경 사항은 업데이트된 ONTAPI to Rest 매핑 문서에도 포함되어 있습니다.
향상된 온라인 설명서:: 이제 ONTAP 온라인 설명서 참조 페이지에는 ONTAP 9.9.1의 새로운 기능을 포함하여 각 REST 엔드포인트 또는 매개 변수가 도입되었을 때 ONTAP 릴리스를 나타내는 레이블이 포함되어 있습니다.




== ONTAP 9.8

ONTAP 9.8은 ONTAP REST API의 폭과 깊이를 크게 확장합니다. 이 솔루션에는 ONTAP 스토리지 시스템의 구축 및 관리를 자동화할 수 있도록 향상된 몇 가지 새로운 기능이 포함되어 있습니다. 또한 기존 ONTAPI API에서 REST로의 전환을 지원하기 위해 지원이 향상되었습니다.

ONTAP 9 REST API에 ONTAPI 매핑:: ONTAPI 자동화를 업데이트할 수 있도록 NetApp에서는 하나 이상의 입력 매개 변수가 필요한 ONTAPI 호출 목록과 해당 호출을 동등한 ONTAP 9 REST API 호출에 대한 매핑을 제공합니다. 을 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2874886["ONTAPI를 REST API 매핑에 매핑"^] 를 참조하십시오.
새로운 ONTAP 9.8 핵심 기능을 위한 API 엔드포인트:: REST API에는 ONTAPI를 통해 사용할 수 없는 새로운 핵심 ONTAP 9.8 기능에 대한 지원이 추가되었습니다. 여기에는 ONTAP S3 버킷 및 서비스, SnapMirror 비즈니스 연속성 및 파일 시스템 분석에 대한 REST API 지원이 포함됩니다.
강화된 보안을 위한 지원 확대:: Azure Key Vault, Google Cloud Key Management Services, IPSec 및 인증서 서명 요청 등의 여러 서비스와 프로토콜을 지원함으로써 보안이 향상되었습니다.
단순성 개선:: ONTAP 9.8은 REST API를 사용하여 보다 효율적이고 현대적인 워크플로를 제공합니다. 예를 들어, OneClick 펌웨어 업데이트는 이제 여러 가지 유형의 펌웨어에서 사용할 수 있습니다.
향상된 온라인 설명서:: 이제 ONTAP 온라인 설명서 페이지에는 9.8의 새로운 기능을 포함하여 각 REST 엔드포인트 또는 매개 변수가 도입된 ONTAP 릴리스를 나타내는 레이블이 포함되어 있습니다.
ONTAPI에서 REST로 전환하기 위한 지원이 향상되었습니다:: 더 많은 레거시 ONTAPI 호출은 이제 상응하는 REST API를 갖습니다. 기존 ONTAPI 호출 대신 어떤 REST 엔드포인트를 사용해야 하는지 파악하는 데도 도움이 되는 문서도 제공됩니다.
성능 메트릭 확장:: REST API의 성능 메트릭을 확장하여 몇 가지 새로운 스토리지 및 네트워크 객체를 포함시켰습니다.




== ONTAP 9.7

ONTAP 9.7은 각각 여러 개의 REST 엔드포인트를 포함하는 세 가지 새로운 리소스 범주를 도입하여 ONTAP REST API의 기능 범위를 확장합니다.

* NDMP
* 오브젝트 저장소
* SnapLock


또한 ONTAP 9.7에서는 기존 리소스 범주 중 여러 개에 하나 이상의 새로운 REST 엔드포인트를 도입합니다.

* 클러스터
* NAS
* 네트워킹
* NVMe를 참조하십시오
* 산
* 보안
* 스토리지
* 지원




== ONTAP 9.6

ONTAP 9.6은 ONTAP 9.4에 처음 도입된 REST API 지원을 크게 확장합니다. ONTAP 9.6 REST API는 대부분의 ONTAP 구성 및 관리 작업을 지원합니다.

ONTAP 9.6의 REST API에는 다음과 같은 주요 영역이 포함되어 있습니다.

* 클러스터 설정
* 프로토콜 구성
* 프로비저닝
* 성능 모니터링
* 데이터 보호
* 애플리케이션 인식 데이터 관리

