---
sidebar: sidebar 
permalink: resources/cluster.html 
keywords: cluster resources 
summary: 이러한 API 호출을 사용하여 ONTAP 클러스터와 관련 리소스를 관리할 수 있습니다. 
---
= ONTAP REST API의 클러스터 리소스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 ONTAP 클러스터와 관련 리소스를 관리할 수 있습니다.

.용량 풀
용량 풀 라이센스 모델을 사용하면 공유 풀에서 각 클러스터 노드의 스토리지 용량을 라이센스할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.섀시
섀시는 클러스터를 지원하는 하드웨어 프레임워크입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.클러스터
ONTAP 클러스터에는 하나 이상의 노드와 스토리지 시스템을 정의하는 관련 구성 설정이 포함되어 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.카운터 테이블
ONTAP에 대한 다양한 통계 정보는 Counter Manager 서브시스템에서 캡쳐됩니다. 이 정보에 액세스하여 시스템 성능을 평가할 수 있습니다. 이 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.펌웨어
펌웨어 업데이트 요청의 기록을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.작업
비동기 REST API 요청은 작업에 의해 고정된 백그라운드 작업을 사용하여 수행됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.사용권 인스턴스
각 라이센스는 별도의 패키지로 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.라이센스 관리자
ONTAP 클러스터와 연결된 각 라이센스 관리자 인스턴스와 관련된 구성 및 기타 정보를 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.추가 수익 실적을
라이센스를 통해 특정 ONTAP 기능을 구현할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.중재자 핑
NetApp 콘솔 클라우드 서비스에 ping을 보낼 수 있습니다. 이 리소스 유형은 ONTAP 9.17.1에 새로 추가되었습니다.

.중개자
MetroCluster 와 연결된 미디에이터를 관리할 수 있으며, 미디에이터 인스턴스 추가 또는 제거도 가능합니다. 이 리소스 유형은 ONTAP 9.8에 새로 추가되었으며 9.17.1에서 업데이트되었습니다.

.MetroCluster
스위치오버 또는 스위치백 작업 실행을 비롯한 MetroCluster 배포를 생성하고 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새롭게 추가되었으며 9.11로 업데이트되었습니다.

.MetroCluster 진단 프로그램
MetroCluster 배포에서 진단 작업을 수행하고 결과를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.MetroCluster DR 그룹
MetroCluster DR 그룹과 관련된 작업을 수행할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.MetroCluster 상호 연결
MetroCluster 상호 연결 상태를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.MetroCluster 노드
MetroCluster 배포에서 개별 노드의 상태를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.MetroCluster 작업
MetroCluster 구성에 대해 최근에 실행된 작업의 목록을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.MetroCluster SVM
MetroCluster 구성에서 모든 SVM 쌍에 대한 정보를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.

.노드
ONTAP 클러스터는 하나 이상의 노드로 구성됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.

.NTP 키
NTP(네트워크 시간 프로토콜)는 ONTAP와 신뢰할 수 있는 외부 NTP 시간 서버 간에 공유 개인 키를 사용하도록 구성할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

.NTP 서버
이러한 API 호출을 사용하여 외부 NTP 서버 및 키를 비롯한 ONTAP 네트워크 시간 프로토콜 설정을 구성할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

.동료
피어 객체는 엔드포인트를 나타내고 클러스터 피어링 관계를 지원합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.성능 카운터
이전 ONTAP 릴리즈에서는 시스템의 작동 특성에 대한 통계 정보를 유지했습니다. 9.11.1 릴리스와 함께 정보가 향상되어 이제 REST API를 통해 사용할 수 있습니다. 이 기능은 ONTAP REST API를 Data ONTAP API(ONTAPI 또는 ZAPI)와 패리티에 더 가깝게 만듭니다. 이 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.리소스 태그
태그를 사용하여 REST API 리소스를 그룹화할 수 있습니다. 이렇게 하면 특정 프로젝트 또는 조직 그룹 내의 관련 자원을 연결할 수 있습니다. 태그를 사용하면 리소스를 보다 효율적으로 구성 및 추적할 수 있습니다. 이 리소스 유형은 ONTAP 9.13에서 도입되었습니다.

.스케줄
일정을 사용하여 작업 수행을 자동화할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.센서
이러한 끝점을 사용하여 모든 플랫폼 환경 센서에 대한 세부 정보를 검색할 수 있습니다. 이 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.소프트웨어
ONTAP 클러스터에는 클러스터 소프트웨어 프로필, 소프트웨어 패키지 컬렉션, 소프트웨어 기록 컬렉션이 포함됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.

.웹
이러한 끝점을 사용하여 웹 서비스 구성을 업데이트하고 현재 구성을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.
