---
sidebar: sidebar 
permalink: resources/name_services.html 
keywords: name services resources 
summary: 이러한 API 호출을 사용하여 ONTAP에서 지원하는 이름 서비스를 관리할 수 있습니다. 
---
= 네임 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 ONTAP에서 지원하는 이름 서비스를 관리할 수 있습니다.

.캐시
ONTAP 이름 서비스는 캐싱을 지원하여 성능과 복원력을 높입니다. 이제 REST API를 통해 이름 서비스 캐시를 구성할 수 있습니다. 호스트, UNIX 사용자, UNIX 그룹 및 넷그룹을 비롯한 여러 레벨에서 설정을 적용할 수 있습니다. 이 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.DDNS
DDNS(동적 DNS) 정보를 표시하고 DDNS 하위 시스템을 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.DNS
DNS는 네트워크에서 ONTAP 클러스터의 통합을 지원합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.호스트 레코드입니다
이러한 끝점을 사용하면 지정된 호스트 이름의 IP 주소와 IP 주소의 호스트 이름을 표시할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.

.LDAP를 지원합니다
LDAP 서버를 사용하여 사용자 정보를 유지할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.LDAP 스키마
ONTAP에서 사용하는 LDAP 스키마를 생성, 수정 및 나열할 수 있습니다. 4개의 기본 스키마가 포함되어 있습니다. 이 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.로컬 호스트
이러한 끝점을 사용하여 호스트 이름에 대한 로컬 매핑을 표시하고 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.

.이름 매핑
이름 매핑을 사용하면 이름 도메인의 ID를 다른 이름 도메인으로 매핑할 수 있습니다. 예를 들어 CIFS에서 UNIX로, Kerberos에서 UNIX로, UNIX에서 CIFS로 ID를 매핑할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.넷그룹 파일
넷그룹 파일 세부 정보를 검색하고 SVM용 파일을 삭제할 수 있습니다. 이 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.NIS를 선택합니다
NIS 서버를 사용하여 사용자 및 클라이언트 워크스테이션을 인증할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.Unix 사용자 및 그룹
로컬 UNIX 사용자 및 그룹은 이전 ONTAP 릴리즈의 일부였습니다. 그러나 이제 REST API에 지원이 추가되어 사용자와 그룹을 표시하고 관리할 수 있습니다. 이러한 REST 리소스 유형은 ONTAP 9.9에 도입되었으며 ONTAP 9.10으로 크게 향상되었습니다.
