---
sidebar: sidebar 
permalink: resources/nas.html 
keywords:  
summary:  
---
= NAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 클러스터와 SVM에 대한 CIFS 및 NFS 설정을 관리할 수 있습니다.



==== 감사

SVM에 대해 특정 CIFS 및 NFS 이벤트를 로깅하여 보안을 강화할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== 감사 로그 리디렉션

NAS 감사 이벤트를 특정 SVM으로 리디렉션할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.



==== CIFS 접속

설정된 CIFS 접속 목록을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.



==== CIFS 도메인입니다

CIFS 도메인에 대한 지원이 클러스터 및 SVM 레벨에서 다양한 유형의 엔드포인트로 추가되었습니다. 도메인 구성을 검색할 뿐만 아니라 기본 도메인 컨트롤러를 만들고 제거할 수도 있습니다. 이 리소스 유형은 ONTAP 9.10에서 새로 추가되었습니다.



==== CIFS 홈 디렉토리 검색 경로입니다

CIFS 서버의 SMB 사용자에 대한 홈 디렉토리는 각 사용자에 대한 개별 SMB 공유를 생성하지 않고 생성할 수 있습니다. 홈 디렉토리 검색 경로는 SVM 루트에서 연결되는 절대 경로 집합입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== CIFS 로컬 그룹

CIFS 서버는 공유, 파일 및 디렉토리 액세스 권한을 결정할 때 인증에 로컬 그룹을 사용할 수 있습니다. 이 리소스 유형은 ONTAP 9.9에서 도입되었으며 ONTAP 9.10으로 크게 확장되었습니다.



==== CIFS NetBIOS입니다

클러스터의 NetBIOS 연결에 대한 정보를 표시할 수 있습니다. 세부 정보에는 IP 주소 및 등록된 NetBIOS 이름이 포함됩니다. 이 정보는 이름 확인 문제를 해결하는 데 도움이 될 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.



==== CIFS 서비스

CIFS 서버의 핵심 구성입니다. 이 리소스 유형은 ONTAP 9.6에서 도입되었으며 ONTAP 9.7로 업데이트되었습니다.



==== CIFS 세션 파일

여러 필터링 옵션을 기반으로 CIFS 세션에 대해 열려 있는 파일 목록을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.



==== CIFS 세션

이 API를 사용하여 CIFS 세션에 대한 자세한 정보를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8 REST API에 도입되었으며 ONTAP 9.9로 향상되었습니다.



==== CIFS 섀도 복사본

Microsoft 원격 볼륨 섀도 복사본 서비스는 기존 Microsoft VSS 기능의 확장입니다. VSS 기능을 확장하여 SMB 공유의 섀도우 복제를 지원합니다. 이 기능은 이제 ONTAP REST API를 통해 사용할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.



==== CIFS 공유

CIFS 서버에 정의된 SMB 공유입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== CIFS는 ACL을 공유합니다

CIFS 공유의 폴더 및 파일에 대한 액세스를 제어하는 ACL(액세스 제어 목록)입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== CIFS UNIX symlink 매핑

CIFS와 UNIX 클라이언트 모두 동일한 데이터 저장소를 액세스할 수 있습니다. UNIX 클라이언트가 심볼 링크를 생성할 때 이러한 매핑은 CIFS 클라이언트를 지원하기 위해 다른 파일 또는 폴더에 대한 참조를 제공합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== CIFS 사용자 및 그룹 대량 가져오기

새로운 REST API 엔드포인트를 사용하여 CIFS 로컬 사용자, 그룹 및 그룹 구성원 정보를 대량으로 가져올 수 있을 뿐 아니라 요청 상태를 모니터링할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.



==== 파일 액세스 추적

이러한 API 호출을 사용하여 특정 파일에 대한 액세스를 추적할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.



==== 파일 보안 권한

이러한 API 호출을 사용하면 특정 파일이나 폴더에 대해 Windows 또는 Unix 사용자에게 부여된 유효한 권한을 표시할 수 있습니다. NTFS 파일 보안 및 감사 정책을 관리할 수도 있습니다. 이 리소스 유형은 ONTAP 9.8 REST API에 도입되었으며 ONTAP 9.9로 대폭 향상되었습니다.



==== FPolicy를 참조하십시오

FPolicy는 SVM에서 파일 액세스 이벤트를 모니터링 및 관리하는 데 사용되는 파일 액세스 알림 프레임워크입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== FPolicy 연결

이러한 엔드포인트를 사용하면 외부 FPolicy 서버의 연결 상태 정보를 표시하고 업데이트할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.



==== FPolicy 엔진

FPolicy 엔진을 사용하여 파일 액세스 알림을 받는 외부 서버를 식별할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== FPolicy 이벤트

파일 액세스를 모니터링하는 방법 및 생성되는 이벤트를 식별하는 구성입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== FPolicy 정책

FPolicy 엔진 및 이벤트를 포함한 FPolicy Framework의 요소에 대한 컨테이너입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== 잠금

잠금은 여러 클라이언트가 동시에 같은 파일에 액세스하는 파일에 대한 동시 액세스에 제한을 적용하는 동기화 메커니즘입니다. 이러한 끝점을 사용하여 잠금을 검색하고 삭제할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.



==== NFS 연결 클라이언트 맵

연결된 클라이언트에 대한 NFS 맵 정보는 새 엔드포인트를 통해 사용할 수 있습니다. 노드, SVM, IP 주소에 대한 세부 정보를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.



==== NFS 연결 클라이언트

연결된 클라이언트 목록을 해당 연결 세부 정보와 함께 표시할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.



==== NFS 엑스포트 정책

NFS 엑스포트를 설명하는 규칙을 포함한 정책입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== NFS Kerberos 인터페이스

Kerberos 인터페이스에 대한 구성 설정입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== NFS Kerberos 영역

Kerberos 영역의 구성 설정입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== NFS 서비스

NFS 서버의 핵심 구성입니다. 이 리소스 유형은 ONTAP 9.6에서 도입되었으며 ONTAP 9.7로 업데이트되었습니다.



==== 오브젝트 저장소

S3 이벤트에 대한 감사는 특정 S3 이벤트를 추적하고 기록할 수 있는 보안 개선입니다. S3 감사 이벤트 선택기는 버킷당 SVM 단위로 설정할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.



==== Vscan

바이러스 및 기타 악성 코드로부터 데이터를 보호하는 보안 기능입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== Vscan 온액세스 정책

Vscan 정책을 통해 클라이언트가 액세스할 때 파일 개체를 능동적으로 스캔할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== Vscan 주문형 정책

Vscan 정책을 사용하면 필요에 따라 또는 정해진 일정에 따라 파일 개체를 즉시 스캔할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== Vscan 스캐너 풀

ONTAP와 외부 바이러스 검사 서버 간의 연결을 관리하는 데 사용되는 일련의 속성입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== Vscan 서버 상태

외부 바이러스 검사 서버의 상태입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.
