---
sidebar: sidebar 
permalink: resources/networking.html 
keywords:  
summary:  
---
= 네트워킹
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 클러스터와 함께 사용되는 물리적 및 논리적 네트워킹 리소스를 관리할 수 있습니다.



==== 이더넷 브로드캐스트 도메인

이더넷 브로드캐스트 도메인은 동일한 물리적 네트워크에 속하는 것으로 보이는 물리적 포트 집합입니다. 모든 포트는 도메인의 포트 중 하나에서 브로드캐스트될 때 패킷을 수신합니다. 각 브로드캐스트 도메인은 IPspace의 일부입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== 이더넷 포트

이더넷 포트는 물리적 또는 가상 네트워킹 엔드포인트입니다. 포트를 LAG(Link Aggregate Group)로 결합하거나 VLAN(Virtual LAN)을 사용하여 분리할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.



==== 이더넷 스위치 포트

이더넷 스위치의 포트 정보를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.



==== 이더넷 스위치

ONTAP 클러스터 또는 스토리지 네트워크에 사용되는 이더넷 스위치의 구성을 검색하거나 수정할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.



==== 파이버 채널 인터페이스

파이버 채널 인터페이스는 SVM과 관련된 논리 엔드포인트입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.



==== 파이버 채널 포트

Fibre Channel 포트는 Fibre Channel 네트워크에 연결하는 데 사용되는 ONTAP 노드의 물리적 어댑터입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.



==== HTTP 프록시

SVM 또는 클러스터 IPSpace에 대해 HTTP 프록시를 구성할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.



==== BGP 피어 그룹

Border Gateway Protocol 피어 그룹을 만들고 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.



==== IP 인터페이스

논리 인터페이스(LIF)는 추가 구성 특성을 가진 IP 주소입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.



==== IP 라우트

라우팅 테이블은 트래픽을 목적지로 전달하는 데 사용되는 IP 라우트의 모음입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.



==== IP 서비스 정책

IP 서비스 정책은 특정 LIF에서 사용 가능한 서비스를 정의합니다. 서비스 정책은 SVM 또는 IPspace의 컨텍스트 내에서 구성할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.



==== IPspace

IPspace는 하나 이상의 SVM을 지원하는 네트워킹 공간을 생성합니다. IPspace를 상호 격리하여 보안 및 개인 정보 보호를 제공할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.
