---
sidebar: sidebar 
permalink: resources/security.html 
keywords:  
summary:  
---
= 보안
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 클러스터 및 SVM 보안 설정을 관리할 수 있습니다.

.계정
클러스터 및 SVM에 대한 사용자 계정 모음이 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.계정 이름입니다
범위가 지정된 사용자 계정의 구성입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.Active Directory 프록시
Active Directory 서버에서 SVM 계정 정보를 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

.랜섬웨어 방지
ONTAP는 랜섬웨어 위협이 있을 가능성이 있는 파일을 감지합니다. 여러 종류의 끝점이 있습니다. 이러한 의심되는 파일의 목록을 검색할 수 있을 뿐 아니라 볼륨에서 제거할 수도 있습니다. 이 리소스 유형은 ONTAP 9.10.1에서 도입되었습니다.

.감사
감사 로그 파일에 기록되는 내용을 결정하는 설정입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.감사 대상
이러한 설정은 감사 로그 정보가 원격 시스템 또는 Splunk 서버로 전달되는 방식을 제어합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.감사 메시지
감사 로그 메시지를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.AWS KMS
Amazon Web Services에는 키 및 기타 비밀에 대한 보안 저장소를 제공하는 키 관리 서비스가 포함되어 있습니다. REST API를 통해 이 서비스에 액세스하여 ONTAP에서 클라우드에 암호화 키를 안전하게 저장할 수 있습니다. 또한 NetApp Storage Encryption에 사용되는 인증 키를 생성하고 나열할 수 있습니다. 이 지원은 ONTAP 9.12에 새로 추가되었습니다.

.Azure 키 저장소
이 API 호출 집합을 사용하면 Azure 키 저장소를 사용하여 ONTAP 암호화 키를 저장할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.인증서
API 호출은 ONTAP에서 사용하는 인증서를 설치, 표시 및 삭제하는 데 사용할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

.클러스터 보안
클러스터 전체 보안의 세부 정보를 검색하고 특정 매개 변수를 업데이트할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었으며 ONTAP 9.8로 업데이트되었습니다.

.GCP KMS
이 API 호출 집합을 사용하면 Google 클라우드 플랫폼 키 관리 서비스를 사용하여 ONTAP 암호화 키를 저장하고 관리할 수 있습니다. 이 리소스 유형은 처음에 ONTAP 9.8 REST API에 도입되었습니다. 그러나 이 기능은 다시 설계되었으므로 ONTAP 9.9에서 새로운 리소스 유형을 사용하는 새로운 기능으로 간주됩니다.

.IPsec
IPSec(인터넷 프로토콜 보안)은 기본 IP 네트워크를 통해 두 엔드포인트 간에 보안을 제공하는 프로토콜 모음입니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.IPsec CA 인증서
IPSec CA 인증서를 추가, 제거 및 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 새로 추가되었습니다.

.IPsec 정책
이 API 호출 집합을 사용하여 IPSec 배포에 적용되는 정책을 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.IPsec 보안 연결
이 API 호출 집합을 사용하여 IPSec 배포에 적용되는 보안 연결을 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

.키 관리자 구성
이러한 끝점을 사용하면 키 관리자에 대한 구성을 검색하고 업데이트할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 새로 추가되었습니다.

.주요 관리자
키 관리자를 사용하면 ONTAP 내의 클라이언트 모듈이 안전하게 저장된 키를 사용할 수 있습니다. 이 리소스 유형은 ONTAP 9.6에 도입되었으며 ONTAP 9.7에 맞게 업데이트되었습니다. 인증 키를 지원하기 위해 ONTAP 9.12가 설치된 또 다른 업데이트가 있습니다.

.키 저장소
키 저장소는 키 관리자의 유형을 설명합니다. 이 리소스 유형은 ONTAP 9.10에서 새로 추가되었습니다.

.LDAP 인증
이러한 API 호출은 클러스터 LDAP 서버 구성을 검색하고 관리하는 데 사용됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.로그인 메시지
ONTAP에서 사용하는 로그인 메시지를 표시하고 관리하는 데 사용됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.여러 관리자 검증
여러 관리자 확인 기능은 ONTAP 명령 또는 작업에 대한 액세스를 보호하기 위한 유연한 인증 프레임워크를 제공합니다. 다음 영역에서 액세스 정의, 요청 및 승인을 지원하는 새로운 엔드포인트가 17개 있습니다.

* 규칙
* 요청
* 승인 그룹


여러 관리자가 액세스를 승인할 수 있는 옵션을 제공하면 ONTAP 및 IT 환경의 보안이 향상됩니다. 이러한 자원 유형은 ONTAP 9.11에서 소개되었습니다.

.NIS 인증
이러한 설정은 클러스터 NIS 서버 구성을 검색하고 관리하는 데 사용됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.암호 인증
여기에는 사용자 계정의 암호를 변경하는 데 사용되는 API 호출도 포함됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.역할 인스턴스에 대한 권한입니다
특정 역할에 대한 권한을 관리합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.공개 키 인증
이러한 API 호출을 사용하여 사용자 계정에 대한 공개 키를 구성할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

.역할
역할은 사용자 계정에 권한을 할당하는 방법을 제공합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.역할 인스턴스
역할의 특정 인스턴스입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.SAML 서비스 공급자
SAML 서비스 공급자의 구성을 표시하고 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

.SSH를 클릭합니다
이러한 통화를 통해 SSH 구성을 설정할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

.SSH SVM
이러한 엔드포인트를 사용하면 모든 SVM에 대한 SSH 보안 구성을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.
