---
sidebar: sidebar 
permalink: resources/storage.html 
keywords:  
summary:  
---
= 스토리지
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 물리적 스토리지와 논리적 스토리지를 관리할 수 있습니다.

특정 집계에 대한 기간별 메트릭 데이터를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.6에서 도입되었으며 ONTAP 9.7로 업데이트되었습니다.

애그리게이트 내 WAFL 스토리지의 물리적 복사본 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

Aggregate는 하나 이상의 RAID 그룹으로 구성됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

클러스터의 브리지를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.9에 도입되었습니다.

클러스터의 물리적 디스크입니다. 이 리소스 유형은 ONTAP 9.6에 도입되었으며 ONTAP 9.7 및 9.8로 업데이트되었습니다.

이러한 끝점을 사용하여 파일 클론을 만들고, 분할 상태를 검색하고, 분할 로드를 관리할 수 있습니다. 파일 클론 생성 엔드포인트 리소스는 ONTAP 9.6에서 처음 도입되었으며 ONTAP 9.8로 확장되었습니다. ONTAP 9.10으로 다시 크게 확장되었습니다.

이러한 REST API 엔드포인트를 사용하여 두 FlexVol 볼륨 간 또는 FlexGroup 볼륨 내에서 파일을 이동할 수 있습니다. 요청이 수락되면 진행 상황과 상태를 모니터링할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.

이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.8로 업데이트되었습니다.

FlexCache는 원본 볼륨의 영구 캐시입니다. 이 리소스 유형은 원래 ONTAP 9.6에서 도입되었습니다. HTTP 패치 방법을 통한 수정을 지원하기 위해 ONTAP 9.9 REST API로 지원이 향상되었습니다.

추가 모니터링을 위해 특정 파일을 지정할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

공유 스토리지 풀을 생성하고 클러스터에서 스토리지 풀을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.

클러스터의 스토리지 포트입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었으며 ONTAP 9.11.1로 향상되었습니다.

서비스 품질 정책 구성 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

QoS 워크로드는 QoS에서 추적하는 스토리지 개체를 나타냅니다. QoS 워크플로우를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.

이러한 API 호출을 사용하여 논리적으로 분리된 파일 시스템의 한 유형인 관리 qtree를 호출할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

파일 또는 공간 사용을 제한하거나 추적하는 기법인 할당량에 대한 보고 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

할당량을 적용하는 데 사용되는 규칙입니다. 이 리소스 유형은 ONTAP 9.6에서 도입되었으며 ONTAP 9.7로 업데이트되었습니다.

쉘프 수: 클러스터 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

스냅샷은 정책에 따라 생성됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

스냅샷 스케줄을 제어할 수 있습니다. 이 리소스 유형은 ONTAP 9.8로 새롭게 재설계되었습니다.

클러스터의 스위치를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.9에 도입되었습니다.

클러스터에서 테이프 디바이스를 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.9에 도입되었습니다.

상위 메트릭 엔드포인트를 사용하면 특정 메트릭으로 필터링된 볼륨의 활동을 확인할 수 있습니다. 클라이언트, 디렉토리, 파일 및 사용자를 기준으로 필터링을 수행할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.

이러한 API 호출을 사용하여 전체 볼륨에 적용되는 효율성을 구성할 수 있습니다. 이 리소스 유형은 ONTAP 9.8에서 새로 추가되었습니다.

논리 컨테이너는 클라이언트에 데이터를 제공하는 데 사용됩니다. 이 리소스 유형은 원래 ONTAP 9.6 REST API에서 도입되었습니다. API와 함께 사용되는 많은 매개변수 값이 ONTAP 9.9로 크게 확장되었으며, 여기에는 공간 관리에 사용되는 값이 포함됩니다.

볼륨의 특정 디렉토리에 대한 파일 및 디렉토리 목록을 검색할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었으며 ONTAP 9.8로 업데이트되었습니다.

볼륨에 대한 스냅샷입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.
