---
sidebar: sidebar 
permalink: resources/support.html 
keywords:  
summary:  
---
= 지원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 API 호출을 사용하여 클러스터를 지원하는 데 사용되는 ONTAP 기능을 관리할 수 있습니다.

독립 실행형 응용 프로그램은 POST 요청을 실행하여 ONTAP 시스템에서 EMS 이벤트 및 선택적으로 생성된 AutoSupport 패키지를 기록할 수 있습니다. 이 리소스 유형은 ONTAP 9.11.1에서 도입되었습니다.

자동 업데이트 기능은 최신 소프트웨어 업데이트를 다운로드하고 적용하여 ONTAP 시스템을 최신 상태로 유지합니다. 상태, 구성 및 업데이트를 포함하여 기능을 지원하는 여러 끝점 범주가 있습니다. 이러한 리소스 유형은 ONTAP 9.10에 도입되었습니다.

AutoSupport는 오류와 함께 구성 및 상태 세부 정보를 수집하고 정보를 NetApp에 보고합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

각 노드는 생성 및 검색할 수 있는 AutoSupport 메시지를 유지합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

이러한 API를 사용하여 현재 백업 설정을 검색하고 업데이트할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

구성 백업 파일을 생성, 검색 및 삭제할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

이러한 엔드포인트를 사용하여 클러스터 또는 노드에서 생성한 메모리 코어 덤프를 검색하고 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.10에서 도입되었습니다.

EMS(이벤트 관리 시스템)는 이벤트를 수집하고 하나 이상의 대상에 알림을 보냅니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 대상은 알림을 보내는 방법과 위치를 결정합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 대상 인스턴스는 유형 및 위치에 따라 정의됩니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

클러스터에 대한 시스템 이벤트의 실시간 모음입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 필터는 추가 처리가 필요한 이벤트를 종합적으로 식별합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 필터 인스턴스는 이벤트에 적용되는 규칙의 모음입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 이벤트 카탈로그에 대한 액세스를 제공합니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 필터의 특정 인스턴스에 대해 규칙 목록을 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

EMS 필터의 특정 인스턴스에 대한 개별 규칙입니다. 이 리소스 유형은 ONTAP 9.6으로 도입되었습니다.

클러스터에 대한 SNMP 및 트랩 작업을 설정하거나 해제할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

SNMP 트랩 호스트는 ONTAP에서 SNMP 트랩을 수신하도록 구성된 시스템입니다. 호스트를 검색하고 정의할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

특정 SNMP 트랩 호스트를 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

SNMP 사용자를 정의하고 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.

엔진 ID가 관리 SVM 또는 데이터 SVM과 관련된 특정 SNMP 사용자를 관리할 수 있습니다. 이 리소스 유형은 ONTAP 9.7에서 도입되었습니다.
