---
sidebar: sidebar 
permalink: pstk/learn-about-pstk.html 
keywords: overview, powershell, powershell toolkit, install powershell toolkit 
summary: NetApp은 ONTAP 스토리지 시스템을 관리하는 데 사용할 수 있는 PowerShell 애플리케이션용 툴킷을 제공합니다. 이 툴킷은 NetApp 개발자에 의해 만들어졌으며 고객 커뮤니티에서 지원합니다. 
---
= NetApp PowerShell 툴킷에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 ONTAP 스토리지 시스템을 관리하는 데 사용할 수 있는 PowerShell 애플리케이션용 툴킷을 제공합니다. 이 툴킷은 NetApp 개발자에 의해 만들어졌으며 고객 커뮤니티에서 지원합니다.



== 개요

PowerShell은 ONTAP 클러스터의 관리를 자동화하는 또 다른 옵션입니다.

.PowerShell을 사용합니다
PowerShell은 작업 자동화 및 구성 관리에 사용할 수 있는 Microsoft의 프로그래밍 언어입니다. 여기에는 스크립트 언어뿐만 아니라 명령줄 셸 환경이 포함되어 있습니다.

.NetApp ONTAP PowerShell 툴킷
NetApp입니다. ONTAP PowerShell 툴킷에는 NetApp ONTAP용 PowerShell 모듈이 포함되어 있습니다. 이 툴킷은 NetApp AFF 및 FAS 시스템, 일반 하드웨어 및 클라우드를 비롯한 다양한 환경에서 실행되는 ONTAP를 지원합니다. 이 모듈에는 Windows 호스트에서 스토리지 관리를 종합적으로 지원하는 2,400개 이상의 cmdlet이 포함되어 있습니다.



== 다운로드 및 설치

NetApp ONTAP PowerShell 툴킷을 다운로드하고 설치하는 데 사용할 수 있는 두 가지 옵션이 있습니다.

.NetApp 지원
PowerShell 툴킷은 다음 NetApp Support 사이트에서 다운로드할 수 있습니다.

https://mysupport.netapp.com/site/tools/tool-eula/ontap-powershell-toolkit["NetApp 를 참조하십시오. ONTAP PowerShell 툴킷"^]

.PowerShell 갤러리
PowerShell 툴킷은 PowerShell 갤러리에서 다운로드할 수 있습니다.

https://www.powershellgallery.com/packages/NetApp.ONTAP/["NetApp 를 참조하십시오. ONTAP PowerShell 툴킷"^]
