---
sidebar: sidebar 
permalink: migrate/performance-counters.html 
keywords: performance, performance counters 
summary: ONTAP 카운터 관리자를 사용하면 ONTAP 사용자가 성능 카운터 정보에 액세스하고 다양한 ONTAP 성능 카운터 메트릭을 내보낼 수 있습니다. 
---
= 성능 카운터
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 카운터 관리자를 사용하면 ONTAP 사용자가 성능 카운터 정보에 액세스하고 다양한 ONTAP 성능 카운터 메트릭을 내보낼 수 있습니다.

ONTAP 9.11.1 이전에는 ONTAP 카운터 관리자 개체의 전체 세트에 대한 액세스가 ONTAP CLI 및 ONTAPI 인터페이스로 제한됩니다.

ONTAP 9.11.1부터 ONTAP 사용자는 ONTAP REST API를 사용하여 Counter Manager 개체의 세그먼트에 액세스할 수 있습니다. ONTAPI에서 ONTAP REST API로 자동화 스크립트를 마이그레이션하는 사용자는 성능 카운터 데이터가 ONTAPI에 표시되는 방식과 해당 데이터가 REST API에 제공되는 방식 간의 차이점을 이해해야 합니다.

을 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885053["ONTAP 9.12.1 ONTAPI-Rest 카운터 관리자 매핑"^] ONTAP 9.11.1의 REST API에서 사용할 수 있는 ONTAP 카운터 집합에 대한 설명뿐 아니라 ONTAPI와 REST API 소비의 카운터 간 차이점 관련 정보도 제공합니다.



== ONTAPI를 사용하여 성능 카운터에 액세스합니다

ONTAPI에서 소비되는 성능 카운터 데이터는 오브젝트로 그룹화됩니다. 예를 들어, 디스크 4개가 포함된 노드의 경우 디스크 성능 카운터 데이터가 객체로 그룹화됩니다. 시스템의 각 물리 디스크는 해당 개체의 인스턴스를 나타내며, ONTAPI를 사용하여 단일 디스크 인스턴스의 개별 성능 카운터에 액세스할 수 있습니다.



== ONTAP REST API를 사용하여 성능 카운터에 액세스

ONTAP REST API를 사용하면 카운터 관리자 객체를 테이블(예: "디스크")로 액세스할 수 있습니다. 즉, 각 카운터 관리자 개체는 고유한 테이블로 표시되고 해당 카운터 관리자 개체의 인스턴스(예: 시스템의 개별 디스크)는 해당 테이블의 행으로 액세스할 수 있습니다. 각 행에는 해당 인스턴스에 대한 여러 개의 개별 성능 카운터가 포함되어 있습니다. 인스턴스에 대한 단일 성능 카운터를 해당 테이블 행의 필드로 액세스할 수 있습니다.

다음 예에서는 ONTAP REST API를 사용하여 각 성능 카운터에 액세스할 수 있는 방법을 보여 주기 위해 "host_adapter" 카운터 관리자 개체가 표 형식으로 표시됩니다. 시스템에는 여러 호스트 어댑터가 있으며 각 호스트 어댑터에는 고유한 성능 카운터가 있습니다.

|===
| 인스턴스 이름 6+| REST 카운터 


| host_adapter_1 | TOTAL_READ_ops | TOTAL_WRITE_ops | 바이트 _ 읽기 | 바이트 _ 쓰입니다 | MAX_LINK_DATA_RATE | RSCN_COUNT 


| Host_adapter_2 | TOTAL_READ_ops | TOTAL_WRITE_ops | 바이트 _ 읽기 | 바이트 _ 쓰입니다 | MAX_LINK_DATA_RATE | RSCN_COUNT 


| Host_adapter_3 | TOTAL_READ_ops | TOTAL_WRITE_ops | 바이트 _ 읽기 | 바이트 _ 쓰입니다 | MAX_LINK_DATA_RATE | RSCN_COUNT 
|===


== REST API 예제를 통한 구조 이해

다음 REST API 예제를 사용하여 Counter Manager 테이블의 구조를 이해할 수 있습니다. 또한 REST API를 사용하여 사용 가능한 엔드포인트를 검색하고 이를 사용하여 시스템 성능을 파악할 수 있는 방법도 보여 줍니다. 이 예들은 객체와 여기에 포함된 카운터 값에 대한 보다 자세한 정보를 점차적으로 보여주는 호스트 어댑터 카운터 관리자 개체를 탐구합니다. 시스템에서 이러한 예를 시도할 경우 괄호 <>로 표시된 정보에 대한 값을 제공해야 합니다.



=== 사용 가능한 성능 카운터 테이블을 검색합니다

이 REST API 호출을 사용하여 쿼리할 수 있는 모든 카운터 관리자 테이블을 검색할 수 있습니다.

.요청 예:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables'
----
.예제 응답(간결성을 위해 잘림):
[source, json]
----
{
  "records": [
    {
      "name": "copy_manager",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/copy_manager"
        }
      }
    },
    {
      "name": "copy_manager:constituent",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/copy_manager%3Aconstituent"
        }
      }
    },
    {
      "name": "disk",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/disk"
        }
      }
    },
    {
      "name": "host_adapter",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter"
        }
      }
    }
    ...
  ],
  "num_records": 68,
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables"
    }
  }
}
----


=== 개별 성능 카운터 테이블을 쿼리합니다

이 REST API 호출을 사용하여 하나의 특정 테이블(카운터 관리자 개체)에 대한 설명과 메타데이터를 볼 수 있습니다. 이 출력은 테이블의 용도를 설명하고 각 성능 카운터가 테이블 레코드에 있는 정보 유형을 설명합니다. 이 예에서는 'host_adapter' 테이블을 쿼리합니다.

.요청 예:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter'
----
.응답 예:
[source, json]
----
{
  "name": "host_adapter",
  "description": "The host_adapter table reports activity on the Fibre Channel, Serial Attached SCSI, and parallel SCSI Host Adapters the storage system uses to connect to disks and tape drives.",
  "counter_schemas": [
    {
      "name": "bytes_read",
      "description": "Bytes read via Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    },
    {
      "name": "bytes_written",
      "description": "Bytes written via Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    },
    {
      "name": "max_link_data_rate",
      "description": "Max link data rate in Kilobytes per second for Host Adapter",
      "type": "raw",
      "unit": "kb_per_sec"
    },
    {
      "name": "node.name",
      "description": "System node name",
      "type": "string",
      "unit": "none"
    },
    {
      "name": "rscn_count",
      "description": "Number of RSCN(s) received by the FC HBA",
      "type": "raw",
      "unit": "none"
    },
    {
      "name": "total_read_ops",
      "description": "Total number of reads on Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    },
    {
      "name": "total_write_ops",
      "description": "Total number of writes on Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    }
  ],
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables/host_adapter"
    }
  }
}
----


=== 성능 카운터 테이블에서 행을 봅니다

이 REST API 호출을 사용하여 테이블의 행을 볼 수 있습니다. 이 경우 Counter Manager 개체의 인스턴스가 어떤 것인지 알 수 있습니다.

.요청 예:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter/rows'
----
.응답 예:
[source, json]
----
{
  "records": [
    {
      "id": "power-01:0b",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0b"
        }
      }
    },
    {
      "id": "power-01:0c",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0c"
        }
      }
    },
    {
      "id": "power-01:0d",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0d"
        }
      }
    },
    {
      "id": "power-01:0e",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0e"
        }
      }
    }
  ],
  "num_records": 4,
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables/host_adapter/rows"
    }
  }
}
----


=== 특정 Counter Manager 인스턴스를 쿼리합니다

이 REST API 호출을 사용하여 테이블의 특정 Counter Manager 인스턴스에 대한 성능 카운터 값을 볼 수 있습니다. 이 예에서는 시스템의 전원 공급 장치 중 하나에 대한 성능 카운터 정보를 요청합니다.

.요청 예:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter/rows/power-01:0b'
----
.응답 예:
[source, json]
----
{
  "counter_table": {
    "name": "host_adapter"
  },
  "id": "power-01:0b",
  "properties": [
    {
      "name": "node.name",
      "value": "power-01"
    }
  ],
  "counters": [
    {
      "name": "total_read_ops",
      "value": 3600516
    },
    {
      "name": "total_write_ops",
      "value": 3591536
    },
    {
      "name": "bytes_read",
      "value": 86354320000
    },
    {
      "name": "bytes_written",
      "value": 480863081920
    },
    {
      "name": "max_link_data_rate",
      "value": 375000
    },
    {
      "name": "rscn_count",
      "value": 0
    }
  ],
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables/host_adapter/rows/power-01:0b"
    }
  }
}
----