---
sidebar: sidebar 
permalink: migrate/software.html 
keywords:  
summary:  
---
= 툴 및 소프트웨어
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp에서 샘플 Python 스크립트 및 기타 관련 소프트웨어를 제공하여 ONTAPI에서 ONTAP REST API로 마이그레이션하는 데 도움이 됩니다. 이 샘플들 중 가장 중요한 것은 아래에 설명되어 있습니다.


NOTE: 모든 Python 코드 샘플은 에서 사용할 수 있습니다 https://github.com/NetApp/ontap-rest-python["NetApp ONTAP REST Python"^] GitHub 리포지토리.

.ONTAPI 사용 보고 도구
ONTAPI 사용 보고 툴은 NetApp 프로페셔널 서비스, 고객 및 파트너가 ONTAP 환경에서 ONTAPI 사용을 식별할 수 있도록 설계되었습니다. 스크립트는 아래 표에 설명된 세 가지 사용 사례에 대해 제공됩니다.

[cols="20,80"]
|===
| 스크립트 | 설명 


| apache_scraper.py | ONTAP 노드에 대해 실행된 ONTAPI 호출을 찾기 위한 Apache 로그 스크레이퍼입니다 


| session_stats.py | ONTAP에서 세션 통계 데이터를 검색하는 CLI 스크립트입니다 


| zapi_to_rest.py | 전달된 ONTAPI 호출 및 속성의 나머지 세부 정보를 추출하기 위한 스크립트입니다 
|===
을 참조하십시오 https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool["ONTAPI 사용 보고 도구"^] 를 참조하십시오.

.전용 CLI를 통과합니다
REST API는 ONTAP에서 사용할 수 있는 다양한 기능과 시설을 제공합니다. 그러나 REST API를 통해 ONTAP CLI에 직접 액세스하는 것이 유용한 경우가 있을 수 있습니다.

이 기능에 대한 소개는 를 참조하십시오 link:../rest/access_ontap_cli.html["REST API를 통해 ONTAP CLI에 액세스합니다"]. Python 샘플은 을 참조하십시오 https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["REST CLI 통과 샘플입니다"^].

.Python 클라이언트 라이브러리
Python 클라이언트 라이브러리는 Python을 사용하여 ONTAP REST API에 설치하고 액세스하는 데 사용할 수 있는 패키지입니다. 이를 통해 ONTAP 배포를 자동화하기 위한 강력한 코드를 빠르게 개발할 수 있습니다.

Python 클라이언트 라이브러리에 대한 소개는 을 참조하십시오 link:../python/overview_pcl.html["Python 클라이언트 라이브러리 개요"]. Python 샘플은 을 참조하십시오 https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Python 클라이언트 라이브러리의 예"^].
