---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: ONTAP 스토리지 시스템의 구축 및 관리를 자동화하는 방법에 대한 자세한 내용을 확인하고 도움을 받을 수 있는 몇 가지 추가 리소스가 있습니다. 
---
= ONTAP REST API에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템의 구축과 관리를 자동화하는 데 도움이 되는 몇 가지 추가 리소스가 있습니다.



== 블로그 기사를 참조하십시오

블로그 문서는 주제에 따라 여러 섹션으로 정렬됩니다.



=== 일반

* 현재 ONTAP 자동화 기술에 대한 요약
+
https://www.netapp.com/blog/new-normal-for-automation["새로운 업계 표준이 도입되었습니다"^]



* ONTAP REST API를 사용하여 파일 보안 및 권한 관리를 탐색할 수 있습니다.
+
https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis["ONTAP REST API를 통해 파일 보안 권한 관리 간소화"^]

* ONTAP 이벤트를 모니터링하여 시스템 활동을 계속 파악할 수 있습니다. REST API를 사용하여 이러한 이벤트의 구성 및 관리를 자동화할 수 있습니다.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["ONTAP REST API: 심각도가 높은 이벤트 자동 알림"^]

* REST API를 사용하여 RBAC 보안 환경의 일부로 역할 및 액세스 수준을 구성할 수 있습니다.
+
https://netapp.io/2022/06/26/rbac-using-ontap-rest-apis["ONTAP REST API를 사용한 RBAC(역할 기반 액세스 제어"^]

* 휴식(6회):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["ONTAP REST API 기초"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["ONTAP REST API의 기능"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["포스트맨을 사용하여 ONTAP REST에 대한 실습"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["ONTAPI(ZAPI) 보고 도구"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["전용 CLI 패스스루"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["ONTAP 스토리지를 간편하게 자동화해 주는 5가지 강력한 기능!"^]






=== Python 클라이언트 라이브러리

* NetApp가 ONTAP REST API에 액세스하기 위해 GitHub에서 제공하는 Python 샘플 스크립트 사용에 대한 소개
+
https://netapp.io/2020/04/23/ontap-rest-apis["ONTAP REST API Python 샘플 스크립트를 이제 GitHub에서 사용할 수 있습니다!"^]

* 이 블로그에서는 ONTAP 파이썬 클라이언트 라이브러리의 기능에 대해 소개합니다.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["Python 클라이언트 라이브러리를 사용하여 ONTAP REST API 사용을 간소화합니다"^]

* 다음은 Python 클라이언트 라이브러리 시작에 대한 3부작 블로그 시리즈입니다.
+
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt1["1부"^]
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt2["2부"^]
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt3["3부"^]






=== REST API로 마이그레이션

* NetApp은 매핑 문서를 통해 독점 ONTAPI API API에서 ONTAP REST API로 이동할 수 있도록 지원합니다.
+
https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["ONTAPI - REST 매핑"^]

* REST API를 기반으로 ONTAP 자동화 환경을 변환하는 데 사용할 수 있는 몇 가지 기술이 있습니다.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["ONTAP API에서 ONTAP REST API로 자동화 전환"^]

* CLI 및 ONTAP 사용자가 ONTAP REST API로 전환할 수 있도록 ONTAP는 모든 CLI 명령에 액세스하는 데 사용할 수 있는 전용 REST API 엔드포인트를 제공합니다.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["전용 CLI를 사용하면 ONTAP REST API를 통해 패스스루를 수행할 수 있습니다"^]

* NetApp은 고객과 파트너가 ONTAP REST API로 전환할 수 있도록 지원합니다.
+
https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["ONTAPI Usage Reporting Tool을 사용하여 ONTAPI(ZAPI)에서 전환"^]





== 비디오

* NetApp Python 클라이언트 라이브러리에 대한 소개 및 라이브러리를 사용하여 코드 작성을 시작하는 방법
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* Ansible 인증 모듈을 살펴보십시오.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* NetApp TechComm TV의 비디오 컬렉션입니다.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["NetApp ONTAP 관리를 자동화합니다"^]





== 기술 교육 및 이벤트

* Insight 2022 프레젠테이션(26분)
+
https://media.netapp.com/video-detail/152137a0-4153-59dc-ad7d-232af1785dd5/modernize-your-ontap-storage-management-with-ontap-rest-apis-1837["ONTAP REST API로 ONTAP 스토리지 관리를 현대화하십시오"^]



* INSIGHT 2021 프레젠테이션(31분)
+
https://media.netapp.com/video-detail/f353c28a-2364-5e5e-bf86-5d7ef66360fe/netapp-ontap-save-time-and-simplify-using-rest-apis-brk-1103-3["NetApp ONTAP: REST API를 사용하여 시간을 절약하고 단순화합니다"^]



* NetApp 학습 서비스:
+
https://netapp.sabacloud.com/Saba/Web_spf/NA1PRD0047/app/shared;spf-url=common%2Fledetail%2FSTRSW-ILT-RSTAPI["ONTAP REST API 및 Ansible을 사용하여 스토리지 관리 자동화"^]





== NetApp 기술 자료

* ONTAP REST API에 문제가 발생한 경우 NetApp에 보고할 수 있습니다.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["ONTAP REST API 및 ONTAP REST API Python 클라이언트 라이브러리의 문제를 보고하는 방법"^]

* ONTAP REST API에서 기능 격차를 확인할 경우 API에 대한 새로운 기능을 요청할 수 있습니다.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["ONTAP REST API에 대한 기능을 요청하는 방법"^]


