---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: ONTAP 스토리지 시스템의 구축 및 관리를 자동화하는 방법에 대한 자세한 내용을 확인하고 도움을 받을 수 있는 몇 가지 추가 리소스가 있습니다. 
---
= 추가 리소스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템의 구축과 관리를 자동화하는 데 도움이 되는 몇 가지 추가 리소스가 있습니다.



== ONTAP 9 리소스

* ONTAP 9 제품군에 대한 문서를 제공합니다.
+
https://docs.netapp.com/us-en/ontap-family/["ONTAP 9 제품 설명서"^]

* 현재 릴리즈에 대한 정보가 포함된 ONTAP 9 릴리즈 노트
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 릴리즈 노트"^]

* ONTAP 9를 계획, 관리 및 지원하는 데 필요한 설명서 및 기타 유용한 링크가 포함되어 있습니다.
+
https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["ONTAP 및 ONTAP 시스템 관리자 리소스"^]

* 이전 ONTAP 릴리스에 대한 릴리즈 노트 및 기타 문서에 액세스합니다.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 제품 라이브러리"^]





== ONTAP 9 개발자 리소스

* DevOps 환경에서 Ansible을 시작하는 데 도움이 됩니다.
+
https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps 솔루션"^]

* 키 ONTAPI 호출 및 동등한 REST API 호출에 대한 매핑을 제공합니다. 적절한 ONTAP 릴리스를 선택합니다.
+
link:../migrate/mapping.html["ONTAPI를 REST API 매핑에 매핑"]

* PyPI의 NetApp Python 클라이언트 라이브러리 패키지
+
https://pypi.org/project/netapp-ontap["사용합니다. NetApp ONTAP"^]

* NetApp Python 클라이언트 라이브러리 문서
+
https://library.netapp.com/ecmdocs/ECMLP2886776/html/index.html["9.14.1용 NetApp PCL 설명서"^]

* ONTAP REST API를 사용하는 데 필요한 리소스 및 문서를 제공합니다.
+
https://devnet.netapp.com/restapi.php["NetApp 개발자 네트워크: ONTAP RESTful API"^]





== 블로그 기사를 참조하십시오

* CLI passthrough는 REST API를 사용하여 ONTAP CLI 명령을 실행하는 기술을 제공합니다.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api["전용 CLI를 사용하면 ONTAP REST API를 통해 패스스루를 수행할 수 있습니다"^]

* ONTAP 자동화를 위해 Ansible을 처음 사용하는 경우, 시작하는 것이 좋습니다.
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["NetApp 및 Ansible 시작하기: Ansible을 설치하십시오"^]





== 비디오

* NetApp Python 클라이언트 라이브러리에 대한 소개 및 라이브러리를 사용하여 코드 작성을 시작하는 방법
+
https://www.youtube.com/watch?v=Wws3SB5d9Ss["NetApp ONTAP Python 클라이언트 라이브러리 시작하기"^]

* 이 동영상은 에서 NetApp TV를 통해서도 볼 수 있습니다 link:https://tv.netapp.com/detail/video/6217195551001["Ansible 인증 모듈"^].
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Ansible 인증 모듈을 살펴보십시오.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]




== NetApp 리소스

* 문제 해결 도구, 문서 및 기술 지원 지원을 이용할 수 있습니다.
+
https://mysupport.netapp.com/["NetApp 지원"^]

* ONTAP 9 및 ONTAP REST API 사용과 관련된 액세스 요구 사항 및 호환성 정보
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]

* 기술 보고서, 백서 및 기타 문서에 액세스합니다.
+
http://www.netapp.com/us/library/index.aspx["NetApp 기술 보고서 및 백서 라이브러리"^]


