---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: ONTAP 스토리지 시스템의 구축 및 관리를 자동화하는 방법에 대한 자세한 내용을 확인하고 도움을 받을 수 있는 몇 가지 추가 리소스가 있습니다. 
---
= 추가 리소스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템의 구축 및 관리를 자동화하는 방법에 대한 자세한 내용을 확인하고 도움을 받을 수 있는 몇 가지 추가 리소스가 있습니다.



== ONTAP 9 리소스

* https://docs.netapp.com/us-en/ontap-family/["ONTAP 9 제품 설명서"^]
+
ONTAP 9 제품군에 대한 문서를 제공합니다.

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 릴리즈 노트"^]
+
현재 릴리즈에 대한 정보가 포함된 ONTAP 9 릴리즈 노트

* https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["ONTAP 및 ONTAP 시스템 관리자 리소스"^]
+
ONTAP 9를 계획, 관리 및 지원하는 데 필요한 설명서 및 기타 유용한 링크가 포함되어 있습니다.

* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 제품 라이브러리"^]
+
이전 ONTAP 릴리스에 대한 릴리즈 노트 및 기타 문서에 액세스합니다.





== ONTAP 9 개발자 리소스

* link:../migrate/mapping.html["ONTAPI를 REST API 매핑에 매핑"]
+
키 ONTAPI 호출 및 동등한 REST API 호출에 대한 매핑을 제공합니다. 적절한 ONTAP 릴리스를 선택합니다.

* https://pypi.org/project/netapp-ontap["사용합니다. NetApp ONTAP"^]
+
PyPI의 NetApp Python 클라이언트 라이브러리 패키지

* https://library.netapp.com/ecmdocs/ECMLP2885777/html/index.html["9.13.1 용 NetApp PCL 설명서"^]
+
NetApp Python 클라이언트 라이브러리 문서

* https://devnet.netapp.com/restapi.php["NetApp 개발자 네트워크: ONTAP RESTful API"^]
+
ONTAP Python 클라이언트 라이브러리를 포함하여 ONTAP REST API를 사용하는 데 필요한 리소스 및 문서를 제공합니다.





== 비디오

* https://www.youtube.com/watch?v=Wws3SB5d9Ss["NetApp ONTAP Python 클라이언트 라이브러리 시작하기"^]
+
NetApp Python 클라이언트 라이브러리에 대한 소개와 라이브러리를 사용하여 코드 작성을 시작하는 방법에 대해 알아봅니다.





== NetApp 리소스

* https://mysupport.netapp.com/["NetApp 지원"^]
+
문제 해결 도구, 문서 및 기술 지원 지원을 이용할 수 있습니다.

* https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]
+
ONTAP 9 및 ONTAP REST API 사용과 관련된 액세스 요구 사항 및 호환성 정보

* http://www.netapp.com/us/library/index.aspx["NetApp 기술 보고서 및 백서 라이브러리"^]
+
기술 보고서, 백서 및 기타 문서에 액세스합니다.


