---
sidebar: sidebar 
permalink: sw-tools/nmsdk.html 
keywords: netapp manageability sdk, oncommand workflow automation, oncommand wfa, ontapi, zapi 
summary: NetApp 관리 SDK는 ONTAP 스토리지를 모니터링하고 관리하는 애플리케이션을 개발하기 위한 일련의 ONTAPI API API 호출 세트를 제공합니다. SDK는 OnCommand Workflow Automation 패키지와 함께 ONTAP 시스템 관리를 자동화하기 위한 노력을 지원합니다. 
---
= NetApp 관리 SDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 관리 SDK는 ONTAP 스토리지를 모니터링하고 관리하는 애플리케이션을 개발하기 위한 일련의 ONTAPI API API 호출 세트를 제공합니다. SDK는 OnCommand Workflow Automation 패키지와 함께 ONTAP 시스템 관리를 자동화하기 위한 노력을 지원합니다.


NOTE: NetApp Manageability SDK 및 OnCommand Workflow Automation는 계속 지원되지만, ONTAP REST API는 ONTAP 시스템을 자동화할 때 사용하는 권장 전략적 기술입니다. 을 참조하십시오 link:../migrate/ontapi_disablement.html["ONTAPI 비활성화"] 를 참조하십시오.

.SDK를 다운로드합니다
NetApp Support 사이트 에서 NetApp 관리 SDK를 다운로드할 수 있습니다. SDK는 클라이언트측에서 Python, PowerShell, C, C++, 자바, C#, VB. 네트, 루비. NetApp 관리 SDK에 대한 자세한 내용과 현재 사용 중인 ONTAP 버전에서 지원되는 방법은 상호 운용성 매트릭스 툴을 검토하십시오.

.OnCommand Workflow Automation를 사용합니다
또한 SDK와 함께 제공되는 API를 사용하여 스크립트를 작성하지 않고도 관리 작업을 자동화할 수 있습니다. OnCommand Workflow Automation(OnCommand WFA)는 관리 작업을 구축하고 실행하기 위해 사전 패키지화된 여러 워크플로우를 제공합니다.

.관련 정보
* https://mysupport.netapp.com/site/["NetApp Support 사이트"^]
* https://www.netapp.com/company/interoperability/["NetApp 상호 운용성 매트릭스 툴"^]
* https://mysupport.netapp.com/documentation/docweb/index.html?productID=63638&language=en-US["NetApp Manageability SDK 설명서"^]
* https://www.netapp.com/data-management/oncommand-workflow-automation-documentation/["OnCommand Workflow Automation 설명서 리소스"^]

