---
sidebar: sidebar 
permalink: workflows/prepare_workflows.html 
keywords: workflows, preparation, prepare to use workflows 
summary: ONTAP 워크플로를 라이브 배포와 함께 사용하기 전에 해당 워크플로의 구조와 형식을 잘 알고 있어야 합니다. 
---
= 워크플로우 사용을 준비하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
라이브 ONTAP 배포와 함께 사용하기 전에 워크플로의 구조와 형식을 잘 알고 있어야 합니다.


TIP: ONTAP 릴리스에서 사용하려는 워크플로에서 모든 API 호출을 지원하는지 확인해야 합니다. 을 참조하십시오 link:../reference/api_reference.html["API 참조입니다"] 를 참조하십시오.



== 소개

Workflow _ 은(는) 특정 관리 작업 또는 목표를 달성하는 데 필요한 하나 이상의 단계 시퀀스입니다. ONTAP 워크플로에는 각 작업을 수행하는 데 필요한 핵심 단계와 매개 변수가 포함되어 있습니다. 이 서비스는 ONTAP 자동화 환경을 사용자 지정하기 위한 시작점을 제공합니다.

.단계 유형
ONTAP 워크플로의 각 단계는 다음 유형 중 하나입니다.

* REST API 호출(curl 및 JSON 예 등의 세부 정보 포함)
* 다른 ONTAP 워크플로우를 수행하거나 호출합니다
* 기타 관련 작업(구성 결정 등)


.REST API 호출
대부분의 워크플로 단계는 REST API 호출입니다. 이 단계에서는 curl 예제 및 기타 정보가 포함된 일반적인 형식을 사용합니다. 를 참조하십시오 link:../reference/api_reference.html["API 참조입니다"] REST API 호출에 대한 자세한 내용은

.단일 단계 워크플로우
워크플로는 한 단계만 포함할 수 있습니다. 이러한 _단일 단계 워크플로_는 여러 단계가 포함된 워크플로와 약간 다르게 형식이 지정됩니다. 예를 들어, 명시적인 단계 이름이 제거됩니다. 작업 또는 작업은 워크플로 제목에 따라 명확해야 합니다.



== 입력 변수

워크플로우는 최대한 일반화되도록 설계되어 모든 ONTAP 환경에서 사용할 수 있습니다. 이 점을 고려하여 REST API 호출은 curl 예제 및 기타 입력에 변수를 사용합니다. 그런 다음 REST API 호출을 다양한 ONTAP 환경에 쉽게 조정할 수 있습니다.



=== 기본 URL 형식입니다

curl 또는 프로그래밍 언어를 통해 ONTAP REST API에 직접 액세스할 수 있습니다. 이 경우 기본 URL이 ONTAP 온라인 설명서 또는 System Manager에 액세스할 때 사용하는 URL과 다릅니다.

API에 직접 액세스할 때 도메인 또는 IP 주소에 * API * 를 추가해야 합니다. 예를 들면 다음과 같습니다.

`https://ontap.demo-example.com/api`

을 참조하십시오 link:../get-started/access_rest_api.html["ONTAP REST API 액세스 방법"] 를 참조하십시오.



=== 공통 입력 매개변수

대부분의 REST API 호출에서 일반적으로 사용되는 몇 가지 입력 매개 변수가 있습니다. 이러한 매개 변수는 일반적으로 개별 워크플로에 설명되어 있지 않습니다. 매개 변수에 대해 잘 알고 있어야 합니다. 을 참조하십시오 link:../rest/input_variables.html["API 요청을 제어하는 입력 변수입니다"] 를 참조하십시오.

특정 REST API 호출에 추가 매개 변수가 필요한 경우 각 워크플로에 대한 curl 예제에 대한 추가 입력 매개 변수 * 섹션에 해당 매개 변수가 포함됩니다.



=== 변수 형식

워크플로우 예제에 사용되는 ID 값과 기타 변수는 불투명하며 ONTAP 클러스터마다 다를 수 있습니다. 예제의 가독성을 높이기 위해 실제 값은 사용되지 않습니다. 변수가 대신 사용됩니다. 일관된 형식과 예약된 이름을 기반으로 하는 이 접근 방식은 다음과 같은 이점을 제공합니다.

* curl 및 JSON 샘플은 읽기 쉽고 이해하기 쉽습니다.
* 모든 키워드가 동일한 형식을 사용하므로 빠르게 식별할 수 있습니다.
* 값을 복사하여 재사용할 수 없으므로 보안 노출이 없습니다.


변수 형식은 Bash 셸 환경에서 사용하도록 지정됩니다. 각 변수는 달러 기호로 시작하고 필요에 따라 큰따옴표로 묶습니다. 그러면 Bash에서 인식할 수 있습니다. 대문자는 이름에 일관되게 사용됩니다.

다음은 일반적인 변수 키워드 중 일부입니다. 이 목록은 완전하지 않으며 필요에 따라 추가 변수가 사용됩니다. 그들의 의미는 상황에 따라 분명해야 합니다.

[cols="25,15,60"]
|===
| 키워드 | 유형 | 설명 


| $FQDN_IP입니다 | URL | ONTAP 관리 LIF의 정규화된 도메인 이름 또는 IP 주소 


| $클러스터_ID | 경로 | API 작업이 실행되는 ONTAP 클러스터를 식별하는 UUIDv4 값입니다. 


| $BASIC_AUTH입니다 | 머리글 | HTTP 기본 인증에 사용되는 자격 증명 문자열입니다. 
|===


=== JSON 입력 예

POST 또는 패치를 사용하는 경우와 같은 일부 REST API 호출에는 요청 본문에 JSON 입력이 필요합니다. JSON 입력 예는 명확한 구별을 위해 컬링 예와 별도로 제시됩니다. JSON 입력 예제를 아래 설명된 기술 중 하나와 함께 사용할 수 있습니다.

.로컬 파일에 저장
JSON 입력 예제를 파일로 복사하여 로컬에 저장할 수 있습니다. curl 명령은 를 사용하는 파일을 참조합니다 `--data` 로 파일 이름을 나타내는 값을 가진 매개 변수입니다 `@` 접두어.

.컬링 예제 다음에 터미널에 붙여 넣습니다
먼저 컬을 복사하여 터미널 쉘에 붙여 넣어야 합니다. 그런 다음 예제를 편집하여 를 완전히 제거합니다 `--data` 끝에 매개 변수를 지정하고 로 바꿉니다 `--data-raw` 매개 변수. 마지막으로, 업데이트된 매개 변수가 있는 curl 명령 다음에 오도록 JSON 예제에 복사하여 붙여 넣습니다. 하나의 따옴표를 사용하여 JSON 입력 예제를 래핑해야 합니다.



== 인증 옵션

REST API에 사용할 수 있는 기본 인증 기술은 HTTP 기본 인증입니다. ONTAP 9.14부터 토큰 기반 인증 및 권한 부여와 함께 OAuth 2.0(Open Authorization) 프레임워크를 사용할 수도 있습니다.



=== HTTP 기본 인증

기본 인증을 사용할 때는 각 HTTP 요청에 사용자 자격 증명을 포함해야 합니다. 자격 증명을 보내는 방법에는 두 가지가 있습니다.

.HTTP 요청 헤더를 생성합니다
수동으로 권한 부여 헤더를 생성하고 HTTP 요청에 포함할 수 있습니다. 이는 CLI에서 curl 명령을 사용하거나 자동화 코드와 함께 프로그래밍 언어를 사용할 때 수행할 수 있습니다. 개괄적인 단계는 다음과 같습니다.

. 사용자 및 암호 값을 콜론으로 연결합니다.
+
`admin:david123`

. 전체 문자열을 base64로 변환:
+
`YWRtaW46ZGF2aWQxMjM=`

. 요청 헤더를 작성합니다.
+
`Authorization: Basic YWRtaW46ZGF2aWQxMjM=`



워크플로 컬링 예제에는 사용하기 전에 업데이트해야 하는 * $BASIC_AUTH * 변수가 있는 이 헤더가 포함됩니다.

.curl 매개 변수를 사용합니다
curl을 사용할 때 다른 옵션은 권한 부여 헤더를 제거하고 대신 curl * user * 매개 변수를 사용하는 것입니다. 예를 들면 다음과 같습니다.

`--user username:password`

사용자 환경에 적합한 자격 증명을 대체해야 합니다. 자격 증명은 base64로 인코딩되지 않습니다. 이 매개 변수를 사용하여 curl 명령을 실행하면 문자열이 인코딩되고 Authorization 헤더가 생성됩니다.



=== OAuth 2.0 을 참조하십시오

OAuth 2.0을 사용하는 경우 외부 인증 서버에서 액세스 토큰을 요청하고 각 HTTP 요청에 포함시켜야 합니다. 기본적인 상위 단계는 아래에 설명되어 있습니다. 도 참조하십시오 https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["ONTAP OAuth 2.0 구축 개요"^] OAuth 2.0에 대한 자세한 내용 및 ONTAP와 함께 사용하는 방법

.ONTAP 환경을 준비합니다
REST API를 사용하여 ONTAP에 액세스하기 전에 ONTAP 환경을 준비하고 구성해야 합니다. 상위 수준에서는 다음과 같은 단계가 포함됩니다.

* ONTAP로 보호되는 리소스 및 클라이언트 식별
* 기존 ONTAP REST 역할 및 사용자 정의를 검토합니다
* 인증 서버를 설치하고 구성합니다
* 클라이언트 권한 부여 정의를 설계하고 구성합니다
* ONTAP를 구성하고 OAuth 2.0을 활성화합니다


.액세스 토큰을 요청합니다
ONTAP 및 인증 서버가 정의되고 활성화되어 있으면 OAuth 2.0 토큰을 사용하여 REST API 호출을 수행할 수 있습니다. 첫 번째 단계는 인증 서버에서 액세스 토큰을 요청하는 것입니다. 이 작업은 서버에 기반한 여러 가지 다른 기술 중 하나를 사용하여 ONTAP 외부에서 수행됩니다. ONTAP는 액세스 토큰을 발급하거나 리디렉션을 수행하지 않습니다.

.HTTP 요청 헤더를 생성합니다
액세스 토큰을 얻은 후 권한 부여 헤더를 생성하고 HTTP 요청에 포함할 수 있습니다. curl 또는 프로그래밍 언어를 사용하여 REST API에 액세스하든 관계없이 모든 클라이언트 요청에 헤더를 포함해야 합니다. 다음과 같이 헤더를 생성할 수 있습니다.

`Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSld ...`



== Bash와 함께 예제 사용

워크플로 컬 예제를 직접 사용하는 경우 해당 변수에 포함된 변수를 환경에 적합한 값으로 업데이트해야 합니다. 예제를 수동으로 편집하거나 아래 설명된 대로 Bash 셸을 사용하여 대신 사용할 수 있습니다.


NOTE: Bash를 사용하면 curl 명령마다 한 번 설정하는 대신 셸 세션에서 한 번 변수 값을 설정할 수 있다는 이점이 있습니다.

.단계
. Linux 또는 유사한 운영 체제와 함께 제공되는 Bash 셸을 엽니다.
. 실행할 컬링 예제에 포함된 변수 값을 설정합니다. 예를 들면 다음과 같습니다.
+
`CLUSTER_ID=ce559b75-4145-11ee-b51a-005056aee9fb`

. 워크플로 페이지에서 컬링 예제를 복사하여 셸 터미널에 붙여 넣습니다.
. Enter * 키를 누르면 다음 작업이 수행됩니다.
+
.. 설정한 변수 값으로 대체합니다
.. curl 명령을 실행합니다



