---
sidebar: sidebar 
permalink: workflows/wf_rbac_user_role.html 
keywords:  
summary: 이 워크플로를 사용하여 연결된 REST 역할을 가진 사용자를 만들 수 있습니다. 
---
= 역할이 있는 사용자를 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 워크플로를 사용하여 연결된 REST 역할을 가진 사용자를 만들 수 있습니다.

.이 워크플로 정보
이 워크플로에는 사용자 지정 REST 역할을 만들고 새 사용자 계정과 연결하는 데 필요한 일반적인 단계가 포함되어 있습니다. 사용자와 역할 모두 SVM 범위를 가지고 있으며 특정 데이터 SVM과 연관됩니다. 일부 단계는 선택 사항이거나 환경에 따라 변경해야 할 수 있습니다.



== 1단계: 클러스터의 데이터 SVM을 나열합니다

다음 REST API 호출을 수행하여 클러스터에 SVM을 표시합니다. 각 SVM의 UUID 및 이름은 출력에 제공됩니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /api/svm/sSVM 
|===
.컬의 예
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/svm/svms?order_by=name" \
-- include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.작업을 마친 후
새 사용자 및 역할을 생성할 목록에서 원하는 SVM을 선택합니다.



== 2단계: SVM에 정의된 사용자를 나열합니다

다음 REST API 호출을 수행하여 선택한 SVM에 정의된 사용자를 나열할 수 있습니다. 소유자 매개 변수를 통해 SVM을 식별할 수 있습니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /api/security/accounts 
|===
.컬의 예
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/security/accounts?owner.name=dmp" \
-- include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.작업을 마친 후
SVM에 이미 정의된 사용자를 기준으로 새 사용자의 이름을 선택합니다.



== 3단계: SVM에 정의된 REST 역할 나열

선택한 SVM에 정의된 역할을 나열하려면 다음 REST API 호출을 수행합니다. 소유자 매개 변수를 통해 SVM을 식별할 수 있습니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /API/보안/역할 
|===
.컬의 예
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/security/roles?owner.name=dmp" \
-- include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.작업을 마친 후
SVM에 이미 정의된 역할에 따라 새 역할에 맞는 고유한 이름을 선택하십시오.



== 4단계: 사용자 지정 REST 역할을 만듭니다

SVM에서 맞춤형 REST API를 생성하여 다음 REST API 호출을 수행합니다. 이 역할에는 처음에 모든 액세스가 거부되도록 기본 액세스 권한을 * 없음 * 으로 설정하는 하나의 권한만 있습니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /API/보안/역할 
|===
.컬의 예
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/security/roles" \
-- include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON 입력 예
[source, curl]
----
{
  "name": "dprole1",
  "owner": {
    "name": "dmp",
    "uuid": "752d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api", "access": "none"},
  ]
}
----
.작업을 마친 후
필요에 따라 3단계를 다시 수행하여 새 역할을 표시합니다. ONTAP CLI에서 역할을 표시할 수도 있습니다.



== 5단계: 권한을 추가하여 역할을 업데이트합니다

필요에 따라 권한을 추가하여 역할을 수정하려면 다음 REST API 호출을 수행합니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /api/security/roles/{owner.uuid}/{name}/권한 
|===
.컬링 예제에 대한 추가 입력 매개 변수
모든 REST API 호출에 공통되는 매개 변수 외에 다음 매개 변수가 이 단계의 cURL 예에도 사용됩니다.

[cols="25,10,10,55"]
|===
| 매개 변수 | 유형 | 필수 요소입니다 | 설명 


| $SVM_ID입니다 | 경로 | 예 | 역할 정의가 포함된 SVM의 UUID입니다. 


| $ROLE_NAME입니다 | 경로 | 예 | 업데이트할 SVM 내의 역할 이름입니다. 
|===
.컬의 예
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/security/roles/$SVM_ID/$ROLE_NAME/priveleges" \
-- include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON 입력 예
[source, curl]
----
{
  "path": "/api/storage/volumes",
  "access": "readonly"
}
----
.작업을 마친 후
필요에 따라 3단계를 다시 수행하여 새 역할을 표시합니다. ONTAP CLI에서 역할을 표시할 수도 있습니다.



== 6단계: 사용자 생성

사용자 계정 생성을 위해 다음 REST API 호출을 수행합니다. 위에서 생성한 * dprole1 * 역할은 새 사용자와 연결됩니다.


TIP: 역할 없이 사용자를 포함할 수 있습니다. 이 경우 사용자를 수정하여 역할을 할당해야 합니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /api/security/accounts 
|===
.컬의 예
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/security/accounts" \
-- include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON 입력 예
[source, curl]
----
{
  "owner": {"uuid":"daf84055-248f-11ed-a23d-005056ac4fe6"},
  "name": "david",
  "applications": [
      {"application":"ssh",
       "authentication_methods":["password"],
       "second_authentication_method":"none"}
  ],
  "role":"dprole1",
  "password":"netapp123"
}
----
.작업을 마친 후
새 사용자의 자격 증명을 사용하여 SVM 관리 인터페이스에 로그인할 수 있습니다.
