---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: accessing the rest api, lif 
summary: 여러 가지 방법으로 ONTAP REST API에 액세스할 수 있습니다. 
---
= ONTAP REST API 액세스 방법
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
여러 가지 방법으로 ONTAP REST API에 액세스할 수 있습니다.



== 네트워크 고려 사항

다음 인터페이스를 통해 REST API에 연결할 수 있습니다.

* 클러스터 관리 LIF
* 노드 관리 LIF
* SVM 관리 LIF


사용할 LIF는 HTTPS 관리 프로토콜을 지원하도록 구성해야 합니다. 또한 네트워크의 방화벽 구성에서 HTTPS 트래픽을 허용해야 합니다.


TIP: 클러스터 관리 LIF는 항상 사용해야 합니다. 이렇게 하면 모든 노드에서 API 요청의 로드 밸런싱을 수행하고 오프라인이거나 연결 문제가 발생하는 노드를 피할 수 있습니다. 여러 클러스터 관리 LIF가 구성된 경우 REST API에 액세스하는 것과 동일한 것입니다.



== ONTAP API 온라인 설명서 페이지

ONTAP API 온라인 설명서 페이지는 웹 브라우저를 사용할 때 액세스 포인트를 제공합니다. 개별 API 호출을 직접 실행하는 방법을 제공하는 것 외에도 이 페이지에는 각 호출에 대한 입력 매개 변수 및 기타 옵션을 포함하여 API에 대한 자세한 설명이 포함되어 있습니다. API 호출은 기능 범주로 구성됩니다. 을 참조하십시오 link:../resources/overview_categories.html["나머지 리소스 요약"] 를 참조하십시오.

최신 버전의 API에 대한 설명서 페이지에 액세스하는 데 사용되는 URL 형식은 다음과 같습니다.

`\https://<cluster_mgmt_ip_address>/docs/api`



== 사용자 정의 소프트웨어 및 도구

여러 가지 프로그래밍 언어 및 도구를 사용하여 ONTAP API에 액세스할 수 있습니다. Python, Java, Curl, PowerShell을 비롯한 다양한 옵션이 제공됩니다. API를 사용하는 프로그램, 스크립트 또는 도구는 REST 웹 서비스 클라이언트로 작동합니다. 프로그래밍 언어를 사용하면 API를 보다 심층적으로 이해할 수 있으며 ONTAP 관리를 자동화할 수 있습니다.

최신 버전의 API에 직접 액세스하는 데 사용되는 기본 URL의 형식은 다음과 같습니다.

`\https://<cluster_mgmt_ip_address>/api`

여러 버전이 지원되는 특정 API 버전에 액세스하려면 URL 형식은 다음과 같습니다.

`\https://<cluster_mgmt_ip_address>/api/v1`
