---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog, netapp, console 
summary: ONTAP 스토리지 시스템의 구축과 관리를 자동화하는 몇 가지 옵션을 사용할 수 있습니다. 
---
= ONTAP 자동화 옵션을 이해합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 스토리지 시스템의 구축과 관리를 자동화하는 몇 가지 옵션을 사용할 수 있습니다.



== ONTAP REST API를 참조하십시오

ONTAP 9.6부터 ONTAP 에는 스토리지 시스템의 배포 및 관리를 자동화하기 위한 기반을 제공하는 강력한 REST API가 포함되어 있습니다.  그 이후로 REST API는 계속 확장되고 발전해 왔습니다.  이제 ONTAP 배포 관리를 자동화할 때 선호되는 전략적 옵션을 제공합니다.

.REST API에 기본적으로 액세스합니다
REST 클라이언트를 지원하는 모든 프로그래밍 언어를 사용하여 ONTAP REST API에 직접 액세스할 수 있습니다. Python, PowerShell, Java 등 다양한 언어가 제공됩니다.

.REST를 사용하도록 레거시 ONTAPI 코드를 마이그레이션합니다
ONTAPI API(Zephyr API 또는 ZAPI)는 NetApp ONTAP 소프트웨어에 포함된 독점 호출 세트로, 데이터 스토리지 관리 및 관리 작업의 자동화를 지원합니다.  API는 다음의 일부입니다.link:../sw-tools/learn-about-nmsdk.html["NetApp 관리 SDK"] .  ONTAPI API를 사용하는 기존 코드가 있는 경우 REST API에서 제공하는 확장된 기능 세트를 활용하기 위해 ONTAP REST API로 마이그레이션을 계획해야 합니다.  NetApp 최신 ONTAP REST API를 사용하도록 코드를 변환하는 기능을 지원합니다. 보다 link:../migrate/migration-considerations.html["ONTAPI에서 REST API로 마이그레이션합니다"] 자세한 내용은.



== 클라이언트 소프트웨어 툴킷

NetApp는 ONTAP REST API를 추상화하여 자동화 코드를 더 쉽게 생성할 수 있는 클라이언트 툴킷을 제공합니다. 개발 언어 및 환경에 적합한 언어를 선택해야 합니다.

.Python 클라이언트 라이브러리
Python 클라이언트 라이브러리는 스크립트를 작성하여 ONTAP REST API에 액세스할 때 사용할 수 있는 패키지입니다. 연결 관리, 비동기 요청 처리 및 예외 처리를 비롯한 여러 기본 서비스에 대한 지원을 제공합니다. Python 클라이언트 라이브러리를 사용하면 ONTAP 자동화 목표를 지원하는 강력한 코드를 빠르게 개발할 수 있습니다. 자세한 내용은 을 link:../python/learn-about-pcl.html["Python 클라이언트 라이브러리"] 참조하십시오.

.PowerShell 툴킷
NetApp.ONTAP PowerShell Toolkit을 사용하면 Windows 호스트에서 ONTAP 클러스터 관리를 자동화할 수 있습니다. 자세한 내용은 을 link:../pstk/learn-about-pstk.html["NetApp PowerShell 툴킷에 대해 자세히 알아보십시오"] 참조하십시오.



== 자동화 프레임워크

여러 프레임워크 중 하나를 사용하여 자동화 코드를 만들고 배포할 수 있습니다.

.Ansible
Ansible은 프로비저닝, 구성 관리, 애플리케이션 배포를 지원하는 오픈 소스 소프트웨어 툴입니다. RedHat이 출시하고 이후 인수한 이후 계속 인기를 끌고 있습니다. NetApp은 고객이 ONTAP 스토리지 시스템 관리를 자동화하는 데 사용할 수 있는 Ansible 인증 모듈을 제공합니다. 을 참조하십시오 link:../additional/learn_more.html["자세한 정보"] 및 https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps 솔루션"^] 자세한 내용은 를 참조하십시오.

.NetApp 콘솔 자동화 카탈로그
NetApp https://console.netapp.com/automationCatalog/["NetApp 콘솔 자동화 카탈로그"^] 콘솔 웹 사용자 인터페이스를 통해 사용할 수 있습니다.  이 카탈로그는 ONTAP 다른 제품과 함께 배포하고 통합하는 과정을 자동화하는 데 도움이 되는 패키지 솔루션에 대한 액세스를 제공합니다.  보다 https://docs.netapp.com/us-en/netapp-automation/["NetApp 자동화"^] 문서 및 자세한 내용은 여기를 참조하세요.
