---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest rest api, python client library, ansible 
summary: ONTAP 9.6부터 ONTAP에는 스토리지 시스템의 배포 및 관리 자동화를 위한 기반을 제공하는 광범위한 REST API가 포함되어 있습니다. REST API에 직접 액세스하거나 NetApp Python 클라이언트 라이브러리를 통해 액세스할 수 있습니다. 
---
= ONTAP 자동화 옵션을 이해합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6부터 ONTAP에는 스토리지 시스템의 배포 및 관리 자동화를 위한 기반을 제공하는 광범위한 REST API가 포함되어 있습니다. REST API에 직접 액세스하거나 NetApp Python 클라이언트 라이브러리를 통해 액세스할 수 있습니다. 또한, NetApp은 Ansible을 사용한 ONTAP 자동화와 기타 고급 소프트웨어 추상화를 지원합니다.


NOTE: 네트워크 관리 SDK 또는 ZAPI라고도 하는 ONTAPI API API는 ONTAP 스토리지 시스템을 프로그래밍 방식으로 액세스 및 관리하기 위한 레거시 기술입니다. ONTAP REST API는 이제 전략적 기술이며 가능한 경우 선택해야 합니다.



== ONTAP REST API에 기본적으로 액세스

REST 클라이언트를 지원하는 모든 프로그래밍 언어를 사용하여 ONTAP REST API에 직접 액세스할 수 있습니다. Python, PowerShell, Java 등 다양한 언어가 제공됩니다. 먼저 이 사이트의 모든 문서를 검토해야 합니다.



== REST를 사용하도록 레거시 ONTAPI 코드를 조정합니다

ONTAPI API를 사용하는 기존 코드가 있는 경우 NetApp은 코드를 변환하여 최신 ONTAP REST API를 사용하도록 지원합니다. 을 참조하십시오 link:../migrate/mapping.html["ONTAPI를 REST API 매핑에 매핑"] ONTAPI 호출을 동등한 REST API 호출에 매핑하는 방법에 대한 자세한 내용은



== NetApp Python 클라이언트 라이브러리 사용

Python 클라이언트 라이브러리는 스크립트를 작성하여 ONTAP REST API에 액세스할 때 사용할 수 있는 패키지입니다. 연결 관리, 비동기 요청 처리 및 예외 처리를 비롯한 여러 기본 서비스에 대한 지원을 제공합니다. Python 클라이언트 라이브러리를 사용하면 ONTAP 자동화 목표를 지원하는 강력한 코드를 빠르게 개발할 수 있습니다. 먼저 이 사이트의 문서를 검토해야 합니다 link:../python/overview_pcl.html["Python 클라이언트 라이브러리"].



== Ansible 사용

Ansible은 프로비저닝, 구성 관리, 애플리케이션 배포를 지원하는 오픈 소스 소프트웨어 툴입니다. RedHat이 출시하고 이후 인수한 이후 계속 인기를 끌고 있습니다. NetApp은 고객이 ONTAP 스토리지 시스템 관리를 자동화하는 데 사용할 수 있는 Ansible 인증 모듈을 제공합니다. 먼저 이 사이트의 문서를 검토해야 합니다 link:../automate/ontap_ansible.html["ONTAP 및 Ansible 자동화"].



== BlueXP 자동화 카탈로그

넷엡 https://console.bluexp.netapp.com/automationCatalog/["BlueXP 자동화 카탈로그"^] 는 BlueXP 웹 사용자 인터페이스를 통해 제공됩니다. 이 카탈로그는 ONTAP 및 기타 NetApp 제품의 자동화된 배포 및 통합을 지원하는 솔루션에 액세스할 수 있습니다. 를 참조하십시오 https://docs.netapp.com/us-en/netapp-automation/["NetApp 자동화"^] 자동화 솔루션에 대한 설명을 보려면 설명서를 참조하십시오.
