---
sidebar: sidebar 
permalink: rest/asynchronous_processing.html 
keywords: asynchronous, asynchronous processing, job, job object 
summary: 비동기적으로 실행되도록 설계된 API 요청을 실행하면 작업 객체가 항상 생성되어 호출자에게 반환됩니다. 이 작업에서는 요청을 처리하는 백그라운드 작업을 설명하고 앵커를 지정합니다. 
---
= 작업 개체를 사용한 비동기 처리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
비동기적으로 실행되도록 설계된 API 요청을 실행하면 작업 객체가 항상 생성되어 호출자에게 반환됩니다. 이 작업에서는 요청을 처리하는 백그라운드 작업을 설명하고 앵커를 지정합니다. HTTP 상태 코드에 따라 작업의 상태를 검색하여 요청이 성공했는지 확인해야 합니다.

을 참조하십시오 link:../reference/api_reference.html["API 참조입니다"] 비동기적으로 수행할 API 호출을 결정합니다.



== 요청 처리 방법 제어

RETURN_TIMEOUT' query 파라미터를 사용하면 비동기 API 호출 처리 방식을 제어할 수 있다. 이 매개 변수를 사용할 경우 두 가지 결과를 얻을 수 있습니다.

요청이 완료되기 전에 타이머가 만료됩니다:: 유효한 요청의 경우 ONTAP는 작업 객체와 함께 202 HTTP 상태 코드를 반환합니다. 요청이 성공적으로 완료되었는지 확인하려면 작업의 상태를 검색해야 합니다.
타이머가 만료되기 전에 요청이 완료되었습니다:: 요청이 유효하고 시간이 만료되기 전에 성공적으로 완료되면 ONTAP는 작업 객체와 함께 200 HTTP 상태 코드를 반환합니다. 요청이 200으로 표시된 대로 동기적으로 완료되므로 작업 상태를 검색할 필요가 없습니다.
+
--

NOTE: RETURN_TIMEOUT 파라미터의 기본값은 0초입니다. 따라서 매개 변수를 포함하지 않으면 유효한 요청에 대해 202 HTTP 상태 코드가 항상 반환됩니다.

--




== API 요청과 관련된 작업 객체를 쿼리합니다

HTTP 응답에서 반환된 작업 개체에는 여러 속성이 포함되어 있습니다. 후속 API 호출에서 state 속성을 쿼리하여 요청이 성공적으로 완료되었는지 확인할 수 있습니다. 작업 오브젝트는 항상 다음 상태 중 하나에 있습니다.

비단말기 상태입니다::
+
--
* 대기열에 있습니다
* 실행 중입니다
* 일시 중지되었습니다


--
터미널 상태::
+
--
* 성공
* 실패


--




== 비동기 요청을 실행하는 일반 절차입니다

다음 고급 절차를 사용하여 비동기 API 호출을 완료할 수 있습니다. 이 예제에서는 RETURN_TIMEOUT 매개변수가 사용되지 않거나 백그라운드 작업이 완료되기 전에 시간이 만료되는 것으로 가정합니다.

. 비동기적으로 수행하도록 설계된 API 호출을 실행합니다.
. 유효한 요청 수락을 나타내는 HTTP 응답 202 을 수신합니다.
. 응답 본문에서 작업 객체의 식별자를 추출합니다.
. 시간 지정 루프 내에서 각 사이클에서 다음을 수행합니다.
+
.. 작업의 현재 상태를 가져옵니다.
.. 작업이 터미널 상태가 아닌 경우 루프를 다시 수행합니다.


. 작업이 터미널 상태(성공, 실패)에 도달하면 중지합니다.


.관련 정보
* link:../workflows/wf_1_update_cluster_contact.html["워크플로우 1: 클러스터 연락처 업데이트 및 작업 상태 확인"]

