---
sidebar: sidebar 
permalink: rest/object_references_and_access.html 
keywords:  
summary:  
---
= 개체 참조 및 액세스
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP REST API를 통해 노출된 리소스 인스턴스 또는 개체는 여러 가지 방법으로 참조되고 액세스할 수 있습니다.



=== 오브젝트 액세스 경로

높은 수준에서는 개체에 액세스할 때 두 가지 경로 유형이 있습니다.

* 기본
+
객체는 API 호출의 기본 또는 직접 타겟입니다.

* 외부
+
객체는 API 호출의 기본 참조가 아니라 기본 객체에서 에 연결됩니다. 따라서 이 개체는 외부 또는 다운스트림 개체이며 기본 개체의 필드를 통해 참조됩니다.





== UUID를 사용하여 개체에 액세스

모든 개체에는 생성 시 고유한 식별자가 할당되며, 대부분의 경우 128비트 UUID입니다. 할당된 UUID 값은 변경할 수 없으며 ONTAP 내에서 내부적으로 사용되어 리소스에 액세스하고 관리할 수 있습니다. 따라서 UUID는 일반적으로 개체에 가장 빠르고 안정적으로 액세스할 수 있습니다.

대부분의 리소스 유형에서 UUID 값을 URL의 경로 키의 일부로 제공하여 특정 개체에 액세스할 수 있습니다. 예를 들어, 다음을 사용하여 노드 인스턴스 ""/cluster/nodes/{uuuid}"에 액세스할 수 있습니다



=== 개체 속성을 사용하여 개체에 액세스

UUID 외에도 개체 속성을 사용하여 개체에 액세스할 수도 있습니다. 대부분의 경우 name 속성을 사용하면 편리합니다. 예를 들어, URL 문자열에 있는 다음 쿼리 매개 변수를 사용하여 노드 인스턴스에 대한 이름("/cluster/nodes?name=node_one")을 기준으로 액세스할 수 있습니다. 쿼리 매개 변수 외에도 기본 개체의 속성을 통해 외부 개체에 액세스할 수 있습니다.

UUID 대신 이름이나 기타 속성을 사용하여 개체에 액세스할 수 있지만 다음과 같은 몇 가지 단점이 있습니다.

* 이름 필드는 변경할 수 없으며 변경할 수 있습니다. 개체에 액세스하기 전에 개체의 이름이 변경되면 잘못된 개체가 반환되거나 개체 액세스 오류가 발생합니다.
+

NOTE: 이 문제는 외부 개체의 POST 또는 패치 메서드나 기본 개체의 get 메서드에서 발생할 수 있습니다.

* ONTAP는 이름 필드를 해당 UUID로 변환해야 합니다. 이는 성능 문제가 될 수 있는 일종의 간접 액세스입니다.


특히 다음 중 하나 이상이 참일 경우 성능 저하가 발생할 수 있습니다.

* Get 메서드가 사용됩니다
* 큰 오브젝트 집합에 액세스합니다
* 복잡하거나 복잡한 쿼리가 사용됩니다




=== 클러스터 및 SVM 컨텍스트 비교

클러스터와 SVM을 모두 지원하는 여러 개의 REST 엔드포인트가 있습니다. 이러한 엔드포인트 중 하나를 사용할 때 'scope=[svm|cluster]' 값을 통해 API 호출 컨텍스트를 나타낼 수 있습니다. 이중 컨텍스트를 지원하는 엔드포인트의 예로는 IP 인터페이스 및 보안 역할이 있습니다.


NOTE: 범위 값에는 각 API 호출에 대해 제공된 속성을 기반으로 하는 기본값이 있습니다.



=== 패치 사용 및 개체 모음에서 삭제

리소스 인스턴스에서 패치나 삭제를 지원하는 모든 REST 끝점은 개체 컬렉션에서 동일한 메서드를 지원합니다. 유일한 요구 사항은 URL 문자열의 쿼리 매개 변수를 통해 하나 이상의 필드를 제공해야 한다는 것입니다. 컬렉션을 통해 패치 또는 삭제를 실행하는 경우 이는 내부적으로 다음을 수행하는 것과 같습니다.

* 쿼리 기반 가져오기 - 컬렉션을 검색합니다
* 컬렉션의 각 개체에 대한 패치 또는 삭제 호출의 일련 번호 시퀀스입니다


작업 제한 시간은 기본값 15초로 RETURN_TIMEOUT으로 설정할 수 있다. 시간 초과 전에 완료되지 않은 경우 응답에는 다음 객체에 대한 링크가 포함됩니다. 작업을 계속하려면 다음 링크를 사용하여 동일한 HTTP 메서드를 다시 실행해야 합니다.
