---
sidebar: sidebar 
permalink: rest/operational_characteristics.html 
keywords: operation, request and response, crud 
summary: 여러 가지 방법으로 ONTAP REST API에 액세스할 수 있습니다. 
---
= 기본 작동 특성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST는 일반적인 기술과 모범 사례를 설정하지만 각 API의 세부 사항은 설계 선택에 따라 달라질 수 있습니다.



== 요청 및 응답 API 트랜잭션

모든 REST API 호출은 클라이언트에 대한 관련 응답을 생성하는 ONTAP 시스템에 대한 HTTP 요청으로 수행됩니다. 이 요청/응답 쌍은 API 트랜잭션으로 간주됩니다. API를 사용하기 전에 요청 및 응답 출력의 내용을 제어하는 데 사용할 수 있는 입력 변수에 대해 잘 알고 있어야 합니다.



== CRUD 작업 지원

ONTAP REST API를 통해 사용 가능한 각 리소스는 CRUD 모델을 기반으로 액세스됩니다.

* 생성
* 읽기
* 업데이트
* 삭제


일부 리소스의 경우 일부 작업만 지원됩니다. 각 리소스에 대한 자세한 내용은 ONTAP 클러스터의 ONTAP API 설명서 페이지를 참조하십시오.



== 오브젝트 식별자

각 리소스 인스턴스 또는 개체는 만들 때 고유한 식별자가 할당됩니다. 대부분의 경우 식별자는 128비트 UUID입니다. 이러한 식별자는 특정 ONTAP 클러스터 내에서 전역적으로 고유합니다. 새 개체 인스턴스를 만드는 API 호출을 실행하면 연결된 ID 값이 있는 URL이 HTTP 응답의 위치 헤더에 있는 호출자에게 반환됩니다. 식별자를 추출하여 리소스 인스턴스를 참조할 때 후속 호출에 사용할 수 있습니다.


NOTE: 개체 식별자의 내용 및 내부 구조는 언제든지 변경할 수 있습니다. 관련 객체를 참조할 때는 필요한 경우 해당 API 호출에서만 식별자를 사용해야 합니다.



== 개체 인스턴스 및 컬렉션

API 호출은 리소스 경로 및 HTTP 메서드에 따라 특정 개체 인스턴스 또는 개체 컬렉션에 적용될 수 있습니다.



== 동기 및 비동기 작업

ONTAP는 클라이언트로부터 받은 HTTP 요청을 수행하는 두 가지 방법이 있습니다.

동기 처리:: ONTAP는 요청을 즉시 수행하고 HTTP 상태 코드가 200 또는 201인 경우 응답한다.
+
--
get , head 및 options 메서드를 사용하는 모든 요청은 항상 동기적으로 수행됩니다. 또한 POST, 패치 및 삭제를 사용하는 요청은 2초 이내에 완료될 것으로 예상되는 경우 동기적으로 실행되도록 설계되었습니다.

--
비동기 처리:: 비동기 요청이 유효한 경우 ONTAP는 요청을 처리하기 위한 백그라운드 작업과 작업을 고정하기 위한 작업 개체를 만듭니다. 202 HTTP 상태는 작업 객체와 함께 호출자에게 반환됩니다. 최종 성공 또는 실패를 확인하려면 작업의 상태를 검색해야 합니다.
+
--
POST, 패치 및 삭제 메서드를 사용하는 요청은 완료하는 데 2초 이상 걸릴 것으로 예상되는 경우 비동기적으로 실행되도록 설계되었습니다.


NOTE: RETURN_TIMEOUT' 쿼리 매개변수는 비동기 API 호출에서 사용할 수 있으며 비동기 호출을 동기적으로 완료하도록 변환할 수 있습니다. 자세한 내용은 작업 개체를 사용한 비동기 처리 작동 방법 을 참조하십시오.

--




== 보안

REST API와 함께 제공되는 보안은 주로 ONTAP에서 사용할 수 있는 기존 보안 기능을 기반으로 합니다. 다음 보안은 API에서 사용됩니다.

전송 계층 보안:: 클라이언트와 ONTAP LIF 간에 네트워크를 통해 전송되는 모든 트래픽은 ONTAP 구성 설정에 따라 TLS를 사용하여 암호화됩니다.
클라이언트 인증:: ONTAP System Manager 및 네트워크 관리 SDK에서 사용할 수 있는 인증 옵션과 동일한 인증 옵션을 ONTAP REST API에서도 사용할 수 있습니다.
HTTP 인증:: 예를 들어, HTTP 레벨에서 ONTAP REST API에 직접 액세스하는 경우 아래에 설명된 대로 두 가지 인증 옵션이 있습니다. 각 경우에 HTTP 권한 부여 헤더를 만들어 각 요청에 포함시켜야 합니다.
+
--
[cols="25,75"]
|===
| 옵션을 선택합니다 | 설명 


| HTTP 기본 인증 | ONTAP 사용자 이름과 암호는 콜론으로 연결됩니다. 문자열은 base64로 변환되고 요청 헤더에 포함됩니다. 


| OAuth 2.0 을 참조하십시오 | ONTAP 9.14부터 외부 권한 부여 서버에서 액세스 토큰을 요청하여 요청 헤더에 베어러 토큰으로 포함할 수 있습니다. 
|===
OAuth 2.0에 대한 자세한 내용과 ONTAP에서 구현하는 방법은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["ONTAP OAuth 2.0 구축 개요"^]. 도 참조하십시오 link:../workflows/prepare_workflows.html["워크플로우 사용을 준비하십시오"] 이 사이트의 아래.

--
ONTAP 인증:: ONTAP는 역할 기반 인증 모델을 구현합니다. ONTAP REST API 또는 API 설명서 페이지에 액세스할 때 사용하는 계정에 적절한 권한이 있어야 합니다.

