---
sidebar: sidebar 
permalink: rest/rbac_wf_create_user.html 
keywords: rbac, workflow, create role, create user 
summary: 아래 설명된 워크플로를 사용하여 연결된 REST 역할이 있는 사용자를 생성할 수 있습니다. 워크플로를 검토하기 전에 일반적인 준비 단계를 숙지해야 합니다. 
---
= 역할이 있는 사용자를 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
아래 설명된 워크플로를 사용하여 연결된 REST 역할이 있는 사용자를 생성할 수 있습니다. 워크플로를 검토하기 전에 일반적인 준비 단계를 숙지해야 합니다.



== 역할이 할당된 ONTAP 사용자를 생성할 준비를 합니다

역할을 만들고 ONTAP 사용자 계정에 할당하기 전에 먼저 주요 보안 요구 사항 및 옵션을 검토하여 준비해야 합니다.

ONTAP 릴리스는 사용 가능한 REST 엔드포인트 및 RBAC 기능을 결정합니다.

보호할 리소스 또는 명령과 범위(클러스터 또는 SVM)를 식별해야 합니다.

리소스 및 범위를 파악한 후에는 부여할 액세스 수준을 결정해야 합니다.

사용자는 REST API 또는 CLI 또는 둘 다를 통해 ONTAP에 액세스할 수 있습니다.

기존 기본 제공 역할을 사용하는 것이 더 편리하지만 필요한 경우 새 사용자 지정 역할을 만들 수 있습니다.

보안 요구 사항 및 ONTAP 액세스를 기반으로 REST 또는 기존 역할을 생성할지 여부를 선택해야 합니다.



== 사용자 지정 역할을 가진 사용자를 만듭니다

아래에 설명된 워크플로에는 사용자 지정 REST 역할을 만들고 이를 새 사용자 계정에 연결하는 데 필요한 일반적인 단계가 포함되어 있습니다. 사용자와 역할 모두 SVM 범위를 가지고 있으며 특정 데이터 SVM과 연관됩니다.


NOTE: 워크플로는 전체 프로세스를 설명하기 위한 것입니다. 일부 단계는 선택 사항이거나 사용자 환경에 따라 변경해야 할 수도 있습니다.



=== 클러스터에 있는 데이터 SVM을 나열합니다

다음 REST API 호출을 수행하여 클러스터에 SVM을 표시합니다. 각 SVM의 UUID 및 이름이 출력에 제공됩니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /api/svm/sSVM 
|===
.컬의 예
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms?order_by=name' -u admin:password -k --header 'Accept: */*'
----
새 사용자 및 역할을 생성할 목록에서 원하는 SVM을 선택합니다.



=== SVM에 정의된 사용자를 나열합니다

다음 REST API 호출을 수행하여 선택한 SVM에 정의된 사용자를 나열할 수 있습니다. 소유자 매개 변수를 통해 SVM을 식별할 수 있습니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /api/security/accounts 
|===
.컬의 예
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/security/accounts/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'
----
SVM에 이미 정의된 사용자를 기준으로 새 사용자의 이름을 선택합니다.



=== SVM에 정의된 나머지 역할을 나열합니다

선택한 SVM에 정의된 역할을 나열하려면 다음 REST API 호출을 수행합니다. 소유자 매개 변수를 통해 SVM을 식별할 수 있습니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /API/보안/역할 
|===
.컬의 예
[source, curl]
----
curl --location -i --request GET 'https://10.222.81.101/api/security/roles/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'
----
SVM에 이미 정의된 역할에 따라 새 역할에 맞는 고유한 이름을 선택하십시오.



=== 사용자 지정 REST 역할을 생성합니다

SVM에서 맞춤형 REST API를 생성하여 다음 REST API 호출을 수행합니다. 이 역할에는 처음에 모든 액세스가 거부되도록 기본 액세스 권한을 * 없음 * 으로 설정하는 하나의 권한만 있습니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /API/보안/역할 
|===
.JSON 입력 예
[source, json]
----
{
  "name": "dprole1",
  "owner": {
    "name": "dmp",
    "uuid": "752d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api", "access": "none"},
  ]
}
----
.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/roles' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
필요에 따라 3단계를 다시 수행하여 새 역할을 표시합니다. ONTAP CLI에서 역할을 표시할 수도 있습니다.



=== 5.더 많은 권한을 추가하여 역할을 업데이트합니다

필요에 따라 권한을 추가하여 역할을 수정하려면 다음 REST API 호출을 수행합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /api/security/roles/{owner.uuid}/{name}/권한 
|===
.JSON 입력 예
[source, json]
----
{
  "path": "/api/storage/volumes", "access": "readonly"}
}
----
.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/roles/752d96be-f17c-11ec-9d19-005056bbad91/dprole1/privileges' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
필요에 따라 3단계를 다시 수행하여 새 역할을 표시합니다. ONTAP CLI에서 역할을 표시할 수도 있습니다.



=== 6.사용자를 생성합니다

사용자 계정 생성을 위해 다음 REST API 호출을 수행합니다. 위에서 만든 역할 dprole1은 새 사용자와 관련이 있습니다.


TIP: 역할 없이 사용자를 포함할 수 있습니다. 이 경우 역할을 할당하기 위해 사용자를 수정해야 합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /api/security/accounts 
|===
.JSON 입력 예
[source, json]
----
{
  "owner": {"uuid":"daf84055-248f-11ed-a23d-005056ac4fe6"},
  "name": "david",
  "applications": [
      {"application":"ssh",
       "authentication_methods":["password"],
       "second_authentication_method":"none"}
  ],
  "role":"dprole1",
  "password":"netapp123"
}
----
.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.222.81.101/api/security/accounts' --data @JSONinput -u admin:password -k --header 'Accept: */*'
----
새 사용자의 자격 증명을 사용하여 SVM 관리 인터페이스에 로그인할 수 있습니다.
