---
sidebar: sidebar 
permalink: rest/rbac_roles_users.html 
keywords: rbac, roles, users, rest endpoints, cli, privileges, access level, cluster, svm 
summary: 기본적인 RBAC 기능을 이해한 후에는 ONTAP 역할 및 사용자 작업을 시작할 수 있습니다. 
---
= 역할 및 사용자 작업
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
기본적인 RBAC 기능을 이해한 후에는 ONTAP 역할 및 사용자 작업을 시작할 수 있습니다.


NOTE: 을 참조하십시오 link:../workflows/wf_rbac_prepare.html["RBAC 워크플로"] ONTAP REST API를 사용하여 역할을 생성하고 사용하는 방법의 예를 참조하십시오.



== 관리 액세스

REST API 또는 명령줄 인터페이스를 통해 ONTAP 역할을 생성하고 관리할 수 있습니다. 액세스 세부 정보는 아래에 설명되어 있습니다.



=== REST API

RBAC 역할 및 사용자 계정으로 작업할 때 사용할 수 있는 여러 엔드포인트가 있습니다. 표의 처음 4개는 역할을 만들고 관리하는 데 사용됩니다. 마지막 두 가지는 사용자 계정을 만들고 관리하는 데 사용됩니다.


TIP: 온라인으로 ONTAP에 액세스할 수 있습니다 link:../reference/api_reference.html["API 참조입니다"] API 사용 방법의 예를 포함한 자세한 내용은 설명서를 참조하십시오.

[cols="35,65"]
|===
| 엔드포인트 | 설명 


| '/security/roles' | 이 끝점을 사용하면 새 REST 역할을 만들 수 있습니다. ONTAP 9.11.1부터 기존 역할을 만들 수도 있습니다. 이 경우 ONTAP는 입력 매개 변수를 기반으로 역할 유형을 결정합니다. 정의된 역할 목록을 검색할 수도 있습니다. 


| '/security/roles/{owner.UUID}/{name}' | 특정 클러스터 또는 SVM 범위 역할을 검색하거나 삭제할 수 있습니다. UUID 값은 역할이 정의된 SVM(클러스터 또는 데이터 SVM)을 식별합니다. 이름 값은 역할의 이름입니다. 


| '/security/roles/{owner.UUID}/{name}/Privileges' | 이 끝점을 사용하면 특정 역할에 대한 권한을 구성할 수 있습니다. 기본 제공 역할은 검색할 수 있지만 업데이트할 수는 없습니다. 자세한 내용은 ONTAP 릴리스의 API 참조 설명서를 참조하십시오. 


| '/security/roles/{owner.UUID}/{name}/Privileges/[path]' | 특정 권한에 대한 액세스 수준 및 선택적 쿼리 값을 검색, 수정 및 삭제할 수 있습니다. 자세한 내용은 ONTAP 릴리스의 API 참조 설명서를 참조하십시오. 


| '/security/accounts' | 이 엔드포인트를 사용하면 새 클러스터 또는 SVM 범위 사용자 계정을 생성할 수 있습니다. 계정이 작동하기 전에 몇 가지 유형의 정보를 포함시키거나 추가해야 합니다. 정의된 사용자 계정 목록을 검색할 수도 있습니다. 


| '/security/accounts/{owner.UUID}/{name}' | 특정 클러스터 또는 SVM 범위 사용자 계정을 검색, 수정, 삭제할 수 있습니다. UUID 값은 사용자가 정의된 SVM(클러스터 또는 데이터 SVM)을 식별합니다. 이름 값은 계정의 이름입니다. 
|===


=== 명령줄 인터페이스입니다

관련 ONTAP CLI 명령어는 다음과 같다. 모든 명령은 클러스터 수준에서 관리자 계정을 통해 액세스합니다.

[cols="30,70"]
|===
| 명령 | 설명 


| 보안 로그인 | 사용자 로그인을 만들고 관리하는 데 필요한 명령이 들어 있는 디렉토리입니다. 


| 보안 로그인 REST 역할 | 사용자 로그인과 관련된 REST 역할을 생성하고 관리하는 데 필요한 명령이 들어 있는 디렉토리입니다. 


| '보안 로그인 역할 | 이 디렉터리는 사용자 로그인과 관련된 기존 역할을 만들고 관리하는 데 필요한 명령이 들어 있는 디렉터리입니다. 
|===


== 역할 정의

나머지 역할과 기존 역할은 일련의 특성을 통해 정의됩니다.

.소유자 및 범위
역할은 ONTAP 클러스터 또는 클러스터 내의 특정 데이터 SVM에서 소유할 수 있습니다. 또한 소유자는 역할의 범위를 암시적으로 결정합니다.

.고유한 이름입니다
모든 역할은 범위 내에서 고유한 이름을 가져야 합니다. 클러스터 역할의 이름은 ONTAP 클러스터 수준에서 고유해야 하며 SVM 역할은 특정 SVM 내에서 고유해야 합니다.


NOTE: 새로운 REST 역할의 이름은 기존 역할과 REST 역할 사이에서 고유해야 합니다. REST 역할을 생성하면 이름이 같은 새로운 기존 _mapping_role도 생성되기 때문입니다.

.권한 집합
모든 역할에는 하나 이상의 권한이 포함됩니다. 각 권한은 특정 리소스 또는 명령과 연결된 액세스 레벨을 식별합니다.



== 권한

역할에는 하나 이상의 권한이 포함될 수 있습니다. 각 권한 정의는 튜플이며 특정 리소스 또는 작업에 대한 액세스 수준을 설정합니다.



=== 리소스 경로입니다

리소스 경로는 REST 엔드포인트 또는 CLI 명령/명령 디렉토리 경로로 식별됩니다.

.REST 엔드포인트
API 끝점이 REST 역할의 대상 리소스를 식별했습니다.

.CLI 명령
CLI 명령은 기존 역할의 타겟을 식별합니다. 명령 디렉토리를 지정할 수도 있습니다. 그러면 ONTAP CLI 계층에 모든 다운스트림 명령이 포함됩니다.



=== 액세스 수준

액세스 수준은 특정 리소스 경로 또는 명령에 대한 역할의 액세스 유형을 정의합니다. 액세스 수준은 사전 정의된 키워드 집합을 통해 식별됩니다. 세 가지 액세스 수준이 ONTAP 9.6에 도입되었습니다. 기존 역할과 REST 역할 모두에 사용할 수 있습니다. 또한 ONTAP 9.11.1을 사용하여 세 가지 새로운 액세스 수준이 추가되었습니다. 이러한 새로운 액세스 수준은 REST 역할에만 사용할 수 있습니다.


NOTE: 액세스 수준은 CRUD 모델을 따릅니다. REST에서는 기본 HTTP 메서드(POST, GET, 패치, 삭제)를 기반으로 합니다. 해당 CLI 작업은 일반적으로 REST 작업(생성, 표시, 수정, 삭제)에 매핑됩니다.

[cols="20,45,15,20"]
|===
| 액세스 수준 | Rest 프리미티브 | 추가되었습니다 | REST 역할만 해당 


| 없음 | 해당 없음 | 9.6 | 아니요 


| 읽기 전용 | 가져오기 | 9.6 | 아니요 


| 모두 | 다운로드, POST, 패치, 삭제 | 9.6 | 아니요 


| read_create 를 참조하십시오 | POST를 완료합니다 | 9.11.1 | 예 


| read_modify 를 참조하십시오 | 패치 | 9.11.1 | 예 


| READ_CREATE_MODIFY을 참조하십시오 | GET, POST, 패치 | 9.11.1 | 예 
|===


=== 선택적 쿼리입니다

기존 역할을 만들 때 * query * 값을 선택적으로 포함하여 명령 또는 명령 디렉터리에 적용할 수 있는 개체의 하위 집합을 식별할 수 있습니다.



== 기본 제공 역할 요약

ONTAP에는 클러스터 또는 SVM 레벨에서 사용할 수 있는 사전 정의된 여러 역할이 포함되어 있습니다.



=== 클러스터 범위 역할

클러스터 범위에는 몇 가지 기본 제공 역할이 있습니다.

을 참조하십시오 https://docs.netapp.com/us-en/ontap/authentication/predefined-roles-cluster-administrators-concept.html["클러스터 관리자를 위한 사전 정의된 역할"^] 를 참조하십시오.

[cols="20,80"]
|===
| 역할 | 설명 


| 관리자 | 이 역할을 가진 관리자는 제한되지 않은 권한을 가지고 있으며 ONTAP 시스템에서 모든 작업을 수행할 수 있습니다. 모든 클러스터 레벨 및 SVM 레벨 리소스를 구성할 수 있습니다. 


| AutoSupport | 이는 AutoSupport 계정에 맞게 조정된 특수 역할입니다. 


| 백업 | 시스템을 백업해야 하는 백업 소프트웨어에 대한 특수 역할입니다. 


| SnapLock | 이는 SnapLock 계정에 맞게 조정된 특수 역할입니다. 


| 읽기 전용 | 이 역할을 가진 관리자는 클러스터 수준에서 모든 항목을 볼 수 있지만 변경할 수는 없습니다. 


| 없음 | 관리 기능은 제공되지 않습니다. 
|===


=== SVM 범위 역할

SVM 범위에는 여러 가지 기본 제공 역할이 있습니다. vsadmin * 은 가장 일반적이고 강력한 기능에 대한 액세스를 제공합니다. 다음과 같은 특정 관리 작업에 맞게 조정된 추가 역할이 몇 가지 있습니다.

* vsadmin - 볼륨
* vsadmin - 프로토콜
* vsadmin - 백업
* vsadmin - SnapLock
* vsadmin - 읽기 전용입니다


을 참조하십시오 https://docs.netapp.com/us-en/ontap/authentication/predefined-roles-svm-administrators-concept.html["SVM 관리자를 위한 사전 정의된 역할"^] 를 참조하십시오.



== 역할 유형 비교

REST * 역할 또는 * 기존 * 역할을 선택하기 전에 차이점을 알고 있어야 합니다. 두 역할 유형을 비교할 수 있는 몇 가지 방법은 아래에 설명되어 있습니다.


NOTE: 고급 또는 복잡한 RBAC 사용 사례의 경우 일반적으로 기존 역할을 사용해야 합니다.



=== 사용자가 ONTAP에 액세스하는 방법

역할을 생성하기 전에 사용자가 ONTAP 시스템에 액세스하는 방법을 알아야 합니다. 이를 바탕으로 역할 유형을 결정할 수 있습니다.

[cols="2,7"]
|===
| 액세스 | 추천 유형입니다 


| REST API만 해당 | REST 역할은 REST API와 함께 사용하도록 설계되었습니다. 


| REST API 및 CLI | REST 역할을 정의하여 이에 상응하는 기존 역할을 생성할 수도 있습니다. 


| CLI만 해당됩니다 | 기존 역할을 생성할 수 있습니다. 
|===


=== 액세스 경로의 정밀도

REST 역할에 대해 정의된 액세스 경로는 REST 엔드포인트를 기반으로 합니다. 기존 역할의 액세스 경로는 CLI 명령 또는 명령 디렉토리를 기반으로 합니다. 또한 선택적 쿼리 매개 변수를 기존 역할과 함께 포함하여 명령 매개 변수 값에 따라 액세스를 추가로 제한할 수 있습니다.
