---
sidebar: sidebar 
permalink: rest/rbac_sample_roles.html 
keywords:  
summary: ONTAP RBAC 기능은 환경에 따라 다른 방법으로 사용할 수 있습니다. 다음은 몇 가지 일반적인 시나리오입니다. 각 경우에는 해당 역할 정의의 예를 통해 특정 보안 및 관리 목표에 초점을 맞춥니다. 
---
= 역할 정의 예
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP RBAC 기능은 환경에 따라 다른 방법으로 사용할 수 있습니다. 다음은 몇 가지 일반적인 시나리오입니다. 각 경우에는 해당 역할 정의의 예를 통해 특정 보안 및 관리 목표에 초점을 맞춥니다.


NOTE: 모든 예제에서는 '/api/security/roles'와 파생된 REST 끝점을 사용하여 역할을 만들고 수정합니다. 명확성을 위해, 각 curl 명령은 별도의 JSON 입력 파일을 참조합니다.



== SVM 볼륨 작업으로 액세스 제한

SVM 내에서 스토리지 볼륨 관리를 제한할 수 있습니다. 아래 예제에서는 처음 만든 다음 선택적으로 업데이트되는 역할을 사용하여 이 작업을 보여 줍니다.



=== 초기 역할을 생성합니다

기존 역할은 클론 생성을 제외한 모든 주요 볼륨 관리 기능에 대한 액세스를 초기에 허용하기 위해 생성됩니다. 아래에 제시된 역할은 다음과 같은 구체적인 특성으로 정의됩니다.

* 가져오기, 생성, 수정 및 삭제를 포함한 모든 CRUD 볼륨 작업을 수행할 수 있습니다
* 볼륨 클론을 생성할 수 없습니다


.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON 입력 예
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      { "path": "volume create", "access": "all" },
      { "path": "volume delete", "access": "all" }
    ]
}
----


=== 역할을 업데이트합니다

사용자가 볼륨 클론을 생성할 수도 있도록 동일한 역할을 수정할 수 있습니다.

.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles/852d96be-f17c-11ec-9d19-005056bbad91/role1/privileges' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON 입력 예
[source, json]
----
{
  "path": "volume clone",
  "access": "all"
}
----


== 데이터 보호 관리

경우에 따라 사용자에게 제한된 데이터 보호 기능을 제공할 수 있습니다. 아래에 나와 있는 기존 역할은 다음과 같은 특징을 통해 정의됩니다.

* SnapMirror 관계를 업데이트할 뿐만 아니라 스냅샷을 생성 및 삭제할 수 있습니다
* 볼륨 또는 SVM과 같은 상위 레벨의 객체를 생성하거나 수정할 수 없습니다


.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON 입력 예
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "volume snapshot create", "access": "all"},
      {"path": "volume snapshot delete", "access": "all"},
      {"path": "volume show", "access": "readonly"},
      {"path": "vserver show", "access": "readonly"},
      {"path": "snapmirror show", "access": "readonly"},
      {"path": "snapmirror update", "access": "all"}
  ]
}
----


== ONTAP 보고서를 생성하는 중입니다

REST 역할을 생성하여 사용자에게 ONTAP 보고서를 생성할 수 있는 기능을 제공할 수 있습니다. 아래에 제시된 역할은 다음과 같은 특성을 가지고 정의됩니다.

* 용량 및 성능(예: 볼륨, qtree, LUN, 애그리게이트, 노드, SnapMirror 관계 포함)
* 더 높은 수준의 오브젝트(예: 볼륨 또는 SVM)를 생성하거나 수정할 수 없음


.컬의 예
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSON 입력 예
[source, json]
----
{
  "name": "rest_role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api/storage/volumes", "access": "readonly"},
      {"path": "/api/storage/qtrees", "access": "readonly"},
      {"path": "/api/storage/luns", "access": "readonly"},
      {"path": "/api/storage/aggregates", "access": "readonly"},
      {"path": "/api/cluster/nodes", "access": "readonly"},
      {"path": "/api/snapmirror/relationships", "access": "readonly"},
      {"path": "/api/svm/svms", "access": "readonly"}
  ]
}
----