---
sidebar: sidebar 
permalink: rest/users_ontapi_api_ontap_cli.html 
keywords: snapdiff, migrating to rest 
summary: ONTAPI는 ONTAP 스토리지 시스템 관리에 사용할 수 있는 네트워크 관리 SDK를 통해 제공되는 API 호출 집합입니다. REST API와 ONTAPI API 호출은 물론 REST API와 ONTAP CLI 간에는 차이점이 있습니다. 
---
= ONTAPI API 및 ONTAP CLI 사용자
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPI는 ONTAP 스토리지 시스템 관리에 사용할 수 있는 네트워크 관리 SDK를 통해 제공되는 API 호출 집합입니다. REST API와 ONTAPI API 호출은 물론 REST API와 ONTAP CLI 간에는 차이점이 있습니다. 운영 환경에서 REST API를 사용하기 전에 이러한 차이점을 이해해야 합니다.



== 일반적인 설계 차이점

ONTAP REST API 및 명령줄 인터페이스는 근본적으로 다른 디자인을 가지고 있습니다. CLI 명령 및 매개 변수는 REST API 호출에 직접 매핑되지 않습니다. 유사성이 있는 경우에도 입력 매개 변수의 세부 정보는 다를 수 있습니다. 예를 들어, 숫자 단위는 바이트로 지정하거나 접미사(예: KB)를 사용할 수 있습니다. 을(를) 검토해야 합니다 link:input_variables.html["API 요청을 제어하는 입력 변수입니다"] 뿐만 아니라 link:../reference/api_reference.html["API 참조입니다"] 를 참조하십시오.



== REST API를 통해 표시되는 데이터 SVM

ONTAP은 다양한 유형의 SVM(스토리지 가상 머신)을 지원합니다. 하지만 ONTAP REST API를 통해 데이터 SVM만 직접 표시됩니다. REST API를 통해 클러스터와 노드를 설명하는 구성 정보를 사용할 수 있지만 클러스터와 노드는 별도의 SVM으로 취급되지 않습니다.



== ONTAPI에서 REST로 마이그레이션

REST API는 ONTAP 시스템 관리 자동화를 위한 주요 전략적 선택입니다. 현재 ONTAPI API를 사용 중인 경우 REST API로 마이그레이션을 고려해야 합니다. NetApp은 ONTAPI에서 REST로의 마이그레이션을 지원하는 매핑 문서를 제공합니다. 을 참조하십시오 link:../migrate/mapping.html["ONTAPI를 REST API 매핑에 매핑"] 를 참조하십시오.



== ONTAPI에서 SnapDiff 가용성 변경

ONTAP 9.10.1부터 SnapDiff v1 및 v2 ONTAPI 호출은 호출할 수 없습니다. SnapDiff v1 또는 v2 ONTAPI 호출을 호출하는 타사 응용 프로그램은 ONTAP 9.10.1부터 작동하지 않습니다. ONTAP 사용자는 ONTAP 9.10.1로 업그레이드하기 전에 백업 응용 프로그램이 SnapDiff v3 REST 호출을 지원하는지 확인해야 합니다.

ONTAP 릴리즈 간 SnapDiff API 가용성은 다음과 같이 정의됩니다.

* ONTAP 9.7 및 이전 릴리즈: v1 및 v2(ONTAPI만 해당)
* ONTAP 9.8–9.9.1:v1, v2 및 v3(ONTAPI와 REST API 모두)
* ONTAP 9.10.1:v3만 해당(REST API만 해당)


자세한 내용은 를 참조하십시오 link:../rn/whats_new.html["ONTAP 릴리즈 노트"].

.관련 정보
* link:../rest/input_variables.html["API 요청을 제어하는 입력 변수입니다"]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2879870["ONTAPI를 통한 REST API 매핑 정보"^]

