---
permalink: manage/dacl-sacl-rest-api.html 
sidebar: sidebar 
keywords: dacl, sacl, permissions, file, api, access, vserver, control, list, access control list, access control 
summary: ONTAP REST API를 사용하여 DACL 및 SACL 파일 권한을 관리합니다. 
---
= ONTAP REST API를 사용하여 DACL 및 SACL 파일 권한을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP에서는 SACL(시스템 액세스 제어 목록) 및 DACL(임의 액세스 제어 목록)을 사용하여 파일 개체에 사용 권한을 할당합니다. ONTAP 9.9.1부터 ONTAP REST API에는 파일에 대한 SACL 및 DACL 권한을 할당하고 파일 보안 권한을 자동화하기 위한 엔드포인트가 포함되어 있습니다. (ONTAP 9.9.1 이전 SACL 및 DACL 권한 자동화 옵션에 대해 자세히 알아볼 수 있습니다 https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["여기"^])를 클릭합니다.

ONTAP 9.9.1부터 여러 CLI 명령 또는 ONTAPI 호출 대신 단일 REST API 호출을 사용할 수 있습니다. 다음 예제에서는 ONTAP REST API를 사용하여 파일 권한을 사용하는 방법을 보여 줍니다. 각 예제에서는 표시된 대괄호 <>에 정보를 입력합니다.

샘플을 참조할 수도 있습니다 https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Python 스크립트"^] 이 부분에서는 여러 SACL 및 DACL 관련 작업을 자동화하는 방법을 보여 줍니다.



== 유효 사용 권한을 봅니다

get/protocols/file-security/Effective-permissions/' API 호출을 이용하여 특정 파일이나 디렉터리에 대한 현재 권한을 조회할 수 있다.

.요청 예:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/effective-permissions/cf5f271a-1beb-11ea-8fad-005056bb645e/administrator/windows/%2F?share.name=sh1&return_records=true'
----
.응답의 예
[source, json]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----


== 모든 감사 정보를 봅니다

get/protocols/file-security/permissions/' API 호출을 이용하여 특정 파일이나 디렉터리에 대한 모든 감사 정보를 조회할 수 있다.

.요청 예:
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent'
----
.응답의 예
[source, json]
----
{
  "svm": {
    "uuid": "9479099d-5b9f-11eb-9c4e-0050568e8682",
    "name": "vs1"
  },
  "path": "/parent",
  "owner": "BUILTIN\\Administrators",
  "group": "BUILTIN\\Administrators",
  "control_flags": "0x8014",
  "acls": [
    {
      "user": "BUILTIN\\Administrators",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    },
    {
      "user": "BUILTIN\\Users",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    }
  ],
  "inode": 64,
  "security_style": "mixed",
  "effective_style": "ntfs",
  "dos_attributes": "10",
  "text_dos_attr": "----D---",
  "user_id": "0",
  "group_id": "0",
  "mode_bits": 777,
  "text_mode_bits": "rwxrwxrwx"
}

----


== 새 사용 권한 적용

'POST/protocols/file-security/permissions/' API call을 이용하여 파일이나 디렉터리에 새로운 보안 설명자를 적용할 수 있다.

.요청 예
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.응답의 예
[source, json]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== 보안 설명자 정보를 업데이트합니다

patch/protocols/file-security/permissions/' API call을 이용하여, primary owner, group, control flags와 같은 파일이나 디렉터리에 대한 특정 보안 설명자 정보를 업데이트할 수 있다.

.요청 예
[source, curl]
----
curl -u admin:<PASSWORD> -X PATCH -d '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.응답의 예
[source, json]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== 기존 SACL/DACL ACE(액세스 제어 항목) 삭제

Delete/protocols/file-security/permissions/' API 호출을 사용하여 디렉토리에 대한 파일에서 기존 ACE를 삭제할 수 있습니다. 이 예제에서는 변경 내용을 자식 개체로 전파합니다.

.요청 예
[source, curl]
----
curl -u admin:<PASSWORD> -X DELETE -d '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent/acl/himanshu?return_timeout=0'
----
.응답의 예
[source, json]
----
{
  "job": {
    "uuid": "e5683b61-5bbf-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/e5683b61-5bbf-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== ONTAP REST API와 ONTAP CLI 명령 비교

ONTAP REST API를 사용하면 대부분의 작업에서 ONTAP CLI보다 더 적은 수의 명령으로 워크플로우를 자동화할 수 있습니다. 예를 들어, 단일 POST API 메서드를 사용하여 여러 CLI 명령을 사용하는 대신 파일에 대한 보안 설명자를 수정할 수 있습니다. 다음 표에는 일반 파일 시스템 권한 작업과 해당 REST API 호출을 완료하는 데 필요한 CLI 명령이 나와 있습니다.

|===
| ONTAP REST API를 참조하십시오 | ONTAP CLI를 참조하십시오 


| 'get/protocols/file-security/Effective-permissions/'  a| 
'vserver security file-directory show-Effective-permissions'를 선택합니다



| 'POST/PROTOCOLS/FILE-SECURITY/permissions/'  a| 
. 'vserver security file-directory NTFS create'
. 'vserver security file-directory NTFS DACL add'
. 'vserver security file-directory NTFS SACL add'
. 'vserver security file-directory policy create'를 참조하십시오
. 'vserver security file-directory policy task add'
. 'vserver security file-directory apply'




| '패치/프로토콜/파일-보안/권한/'  a| 
'vserver security file-directory NTFS modify'를 참조하십시오



| 삭제/프로토콜/파일-보안/권한/'  a| 
. 'vserver security file-directory NTFS DACL remove'
. 'vserver security file-directory NTFS SACL remove'


|===


== 관련 정보

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["ONTAP REST API DACL/SACL 권한 예제 Python 스크립트"^]
* https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis/["ONTAP REST API를 통해 파일 보안 권한 관리 간소화"^]
* https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["ONTAP REST API와 함께 전용 CLI 패스스루 사용(ONTAP 9.9.1 이전 버전의 경우)"^]

