---
permalink: manage/ems-rest-api.html 
sidebar: sidebar 
keywords: ems, configuration, workflow 
summary: REST API를 이용하여 ONTAP EMS 설정을 관리할 수 있다. 
---
= ONTAP REST API로 EMS 이벤트 알림 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP REST API를 사용하여 중요한 EMS(이벤트 관리 시스템) 이벤트 알림이 전송되는 방식을 구성할 수 있으며, 모든 EMS 메시지 또는 특정 속성을 가진 특정 메시지를 검색할 수 있습니다. REST API를 사용하여 EMS 관련 작업을 자동화하여 다른 EMS 메시지 작업 방법에 비해 시간을 절약할 수 있습니다.

다음 예에서는 ONTAP REST API를 사용하여 EMS 메시지를 사용하는 방법을 보여 줍니다. 각 예제에서는 표시된 대괄호 <>에 정보를 입력합니다. 샘플을 참조할 수도 있습니다 https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Python 스크립트"^] 이를 통해 여러 EMS 관련 활동을 자동화하는 방법을 확인할 수 있습니다.



== 특정 이벤트 로그를 봅니다

Get/support/EMS/events API call을 이용하여 최신 메시지, 특정 text가 포함된 메시지, 특정 severity의 메시지 등 특정 event message를 조회할 수 있다.

.요청 예: 최신 메시지를 검색합니다
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?fields=message.name&max_records=1'
----
.응답의 예
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 6260,
      "message": {
        "name": "netinet6.rtr.high.mtu"
      },
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/6260"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?fields=message.name&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-22T10%3A28%3A29-04%3A00&start.node.name=malha-vsim1&start.index=6260&fields=message.name&max_records=1"
    }
  }
}
----
.요청 예: 특정 텍스트 및 심각도를 포함하는 메시지를 검색합니다
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?log_message=*disk*&message.severity=alert'
----
.응답의 예
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----


== 기존 EMS 설정을 확인한다

Get/support/EMS/ API call을 이용하여 기존 EMS notification 설정 정보를 조회할 수 있다.

.요청 예
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/'
----
.응답의 예
[source, json]
----
{
  "proxy_url": "https://proxyserver.mycompany.com",
  "proxy_user": "proxy_user",
  "mail_server": "mail@mycompany.com",
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "pubsub_enabled": "1",
  "mail_from": "administrator@mycompany.com"
}
----


== 새 EMS 알림 설정을 생성한다

여러 API 호출을 함께 사용하여 새 EMS 구성을 만들어 메시지 수신 방법과 시기를 사용자 지정할 수 있습니다.

.단계
. 시스템 전체 이메일 설정을 구성합니다. 예를 들면 다음과 같습니다.
+
[source, curl]
----
curl -X PATCH -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com'
----
. 특정 메시지를 일치시키기 위해 특정 규칙을 사용하는 필터를 정의합니다. 예를 들면 다음과 같습니다.
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-filter", "rules.type": ["include"], "rules.message_criteria.severities": ["emergency"]}' -k 'https://<IP_ADDRESS>/api/support/ems/filters/'
----
. 메시지의 대상을 만듭니다. 예를 들면 다음과 같습니다.
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-destination", "type": "email", "destination": "administrator@mycompany.com", "filters.name": ["important-events"]}' -k 'https://<IP_ADDRESS>/api/support/ems/destinations/'
----




== ONTAP REST API와 ONTAP CLI 명령 비교

ONTAP REST API를 사용하면 대부분의 작업에서 ONTAP CLI보다 더 적은 수의 명령으로 워크플로우를 자동화할 수 있습니다. 예를 들어, 여러 개의 CLI 명령을 사용하는 대신 단일 POST API 메서드를 사용하여 필터를 만들 수 있습니다. 다음 표에는 일반 EMS 작업과 해당 REST API 호출을 완료하는 데 필요한 CLI 명령이 나와 있습니다.

|===
| ONTAP REST API를 참조하십시오 | ONTAP CLI를 참조하십시오 


| 'Get/support/EMS | 이벤트 구성 쇼 


| 'POST/support/EMS/destinations  a| 
. 이벤트 알림 메시지 목적지 작성
. 이벤트 알림 작성




| 'Get/support/EMS/events | 이벤트 로그 쇼 


| 'POST/support/EMS/filters  a| 
. '이벤트 필터 생성 - 필터 이름 <filtername>'
. '이벤트 필터 규칙 add-filter-name <filtername>'


|===


== 관련 정보

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["ONTAP REST API EMS 예제 Python 스크립트"^]
* https://blog.netapp.com/ontap-rest-apis-automate-notification["ONTAP REST API: 심각도가 높은 이벤트 자동 알림"^]

